In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
from pylab import rcParams
sns.set_style("darkgrid")
import json
import requests
from pandas.io.json import json_normalize


import warnings
warnings.filterwarnings("ignore")
warnings.warn("This will not show")

%matplotlib inline

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows',500)
pd.set_option('display.max_info_rows', 500)
pd.set_option('display.max_colwidth', 10)
pd.set_option('display.max_info_columns', 5000)
pd.set_option('display.expand_frame_repr', True)
pd.set_option('display.width', 2000)

# 1.GENERAL INSIGHT

In [3]:
df = pd.read_json('scout_car.json', orient= "records", lines=True)
df.T.head(20)

                0          1          2          3          4          5          6          7          8          9          10         11         12         13         14         15         16         17         18         19         20         21         22         23         24     ...      15894      15895      15896      15897      15898      15899      15900      15901      15902      15903      15904      15905      15906      15907      15908      15909      15910      15911      15912      15913      15914      15915      15916      15917      15918
url         https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  ...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...  https:...
make_model    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1    Audi A1  ...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...  Renaul...
short_d...  Sportb...  1.8 TF...  Sportb...  1.4 TD...  Sportb...  1.6 TD...  Sportb...  Sportb...  SPB 1....  SPORTB...  SPORTB...  Sportb...  Sportb...  1.4 TF...  Sportb...  SPB 1....  SPB 1....  1.4 TD...  1.0 TF...  Sportb...  SPB 1....  Sportb...  1.4 TF...  SPB 1....  SPB 1....  ...  Initia...  dCi 20...  Initia...  INITIA...  Blue d...  2.0 Bl...  ESPACE...  Blue d...  BLUE d...  1.8 TC...  BLUE d...  Energy...  V Tce ...  1.8 TC...  1.8 TC...  Limite...  TCe 22...  ELYSEE...  Blue d...  INITIA...  Blue d...  TCe 22...  Blue d...  Blue d...  INITIA...
body_type      Sedans     Sedans     Sedans     Sedans     Sedans     Sedans  Statio...    Compact     Sedans     Sedans     Sedans     Sedans     Sedans     Sedans     Sedans     Sedans     Sedans     Sedans    Compact     Sedans     Sedans     Sedans     Sedans     Sedans     Sedans  ...        Van  Statio...        Van        Van        Van        Van        Van        Van     Sedans        Van  Statio...    Compact        Van        Van        Van        Van        Van        Van        Van        Van        Van        Van        Van        Van        Van
price           15770      14500      14640      14500      16790      15090      16422      14480      16700      17990      18500      17990      18380      18399      17990      18700      18900      18500      18400      18500      18500      18500      18900      18850      18500  ...      41899      42490      41900      41790      41400      41395      41480      41400      41043      39990      41390      39990      39990      39990      39990      39990      39980      39980      39950      39950      39950      39885      39875      39700      40999
vat         VAT de...  Price ...  VAT de...       None       None       None  VAT de...  VAT de...       None       None  VAT de...       None       None       None  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  Price ...  VAT de...  Price ...  VAT de...  VAT de...  ...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...       None  VAT de...  VAT de...  VAT de...  VAT de...       None  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...  VAT de...
km          56,013 km  80,000 km  83,450 km  73,000 km  16,200 km  63,668 km  62,111 km  14,986 km  57,000 km  16,103 km  11,300 km  26,415 km  31,600 km  45,764 km  34,914 km  27,000 km   9,752 km  28,408 km  50,280 km  13,406 km  51,160 km  15,850 km  17,000 km   9,077 km   3,000 km  ...   4,899 km  16,500 km   5,000 km      10 km      10 km   5,000 km   8,500 km      10 km       - km      10 km      50 km     500 km      10 km      50 km      10 km   3,500 km   8,500 km     100 km       - km   1,000 km       - km   9,900 km      15 km      10 km       - km
registr...    01/2016    03/2017    02/2016    08/2016    05/2016    02/2016    03/2016    02/2016    02/2016    06/2017    05/2018    05/2016    09/2016    06/2016    10/2016    04/2016    06/2018    11/2017    07/2016    05/2018    06/2017    03/2016    12/2016    05/2018    09/2018  ...    04/2019    02/2019        -/-    01/2019    06/2019    03/2019    01/2019    06/2019        -/-    01/2019    04/2019    01/2019    01/2019        -/-    02/2019    05/2019    02/2019    02/2019        -/-    04/2019        -/-    01/2019    03/2019    06/2019    01/2019
prev_owner  2 prev...       None  1 prev...  1 prev...  1 prev...  1 prev...  1 prev...  1 prev...  1 prev...       None       None  1 prev...  1 prev...       None  1 prev...  1 prev...       None  1 prev...       None       None  1 prev...  1 prev...  1 prev...       None  1 prev...  ...       None  1 prev...  1 prev...  1 prev...       None  1 prev...       None       None       None       None       None  1 prev...       None       None       None       None  1 prev...  1 prev...       None       None       None  1 prev...  1 prev...       None  1 prev...
kW                NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  ...        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
hp              66 kW     141 kW      85 kW      66 kW      66 kW      85 kW      85 kW      66 kW      85 kW      70 kW      85 kW      92 kW      92 kW     112 kW      70 kW      85 kW      85 kW      66 kW      70 kW      85 kW      85 kW      92 kW      92 kW      85 kW      70 kW  ...     118 kW     147 kW     118 kW     165 kW     118 kW     147 kW     165 kW     118 kW     147 kW     168 kW     118 kW     165 kW       - kW     165 kW     167 kW     147 kW     165 kW     118 kW     147 kW     165 kW     147 kW     165 kW     146 kW     147 kW     165 kW
Type        [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Emp...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  [, Use...  ...  [, Dem...  [, Dem...  [, Use...  [, Pre...  [, Pre...  [, Dem...  [, Dem...  [, Pre...  [, New...  [, Use...  [, Pre...  [, Dem...  [, Use...  [, New...  [, Use...  [, Dem...  [, Dem...  [, Pre...  [, New...  [, Dem...  [, New...  [, Use...  [, Pre...  [, Pre...  [, Dem...
Previou...      \n2\n        NaN      \n1\n      \n1\n      \n1\n      \n1\n      \n1\n      \n1\n      \n1\n        NaN        NaN      \n1\n      \n1\n        NaN      \n1\n      \n1\n        NaN      \n1\n        NaN        NaN      \n1\n      \n1\n      \n1\n        NaN      \n1\n  ...        NaN      \n1\n      \n1\n      \n1\n        NaN      \n1\n        NaN        NaN        NaN        NaN        NaN      \n1\n        NaN        NaN        NaN        NaN      \n1\n      \n1\n        NaN        NaN        NaN  [\n1\n...  [\n1\n...        NaN      \n1\n
Next In...  [\n06/...        NaN        NaN        NaN        NaN        NaN        NaN        NaN  [\n02/...        NaN        NaN        NaN  [\n09/...        NaN  [\n10/...  [\n04/...        NaN        NaN  \n07/2...        NaN        NaN        NaN  [\n12/...        NaN        NaN  ...        NaN  [\n06/...        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  [\n01/...        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  [\n01/...        NaN        NaN        NaN
Inspect...  [\nYes...        NaN        NaN        NaN  [\nYes...        NaN  [\nYes...  [\nYes...        NaN        NaN        NaN  [\nYes...        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  [\nYes...        NaN        NaN        NaN  ...        NaN  [\nYes...  [\nYes...  [\nYes...        NaN        NaN    \nYes\n        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  [\nYes...        NaN  [\nYes...
Warranty    [\n, \...        NaN  [\n, \...        NaN  [\n, \...        NaN        NaN  [\n, \...  [\n12 ...  \n3 mo...        NaN  [\n, \...  [\n, \...  \n12 m...        NaN  [\n12 ...        NaN        NaN  [\n6 m...         \n  [\n12 ...  [\n12 ...   [\n, \n]         \n        NaN  ...        NaN   [\n, \n]  [\n60 ...        NaN         \n  [\n48 ...        NaN         \n        NaN  \n12 m...        NaN  [\n, \...  \n12 m...  [\n36 ...  \n12 m...  \n48 m...        NaN        NaN  \n24 m...        NaN  \n24 m...  [\n, \...  [\n, \...         \n        NaN
Full Se...   [\n, \n]        NaN        NaN  [\n, \...  [\n, \...  [\n, \...  [\n, \...  [\n, \...        NaN        NaN         \n  [\n, \...        NaN        NaN        NaN   [\n, \n]        NaN  [\n, \...  [\n, \...        NaN  [\n, \...  [\n, \...   [\n, \n]        NaN        NaN  ...        NaN   [\n, \n]        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  [\n, \...        NaN        NaN        NaN        NaN  [\n, \...        NaN        NaN        NaN        NaN        NaN   [\n, \n]        NaN        NaN
Non-smo...   [\n, \n]        NaN        NaN  [\n, \...   [\n, \n]  [\n, \...  [\n, \...        NaN        NaN        NaN        NaN   [\n, \n]  [\n, \...        NaN        NaN   [\n, \n]        NaN        NaN        NaN        NaN   [\n, \n]  [\n, \...   [\n, \n]        NaN  [\n, \...  ...        NaN        NaN  [\n, \...        NaN        NaN        NaN  [\n, \...        NaN  [\n, \...        NaN        NaN   [\n, \n]        NaN        NaN        NaN        NaN  [\n, \...  [\n, \...        NaN        NaN        NaN  [\n, \...   [\n, \n]        NaN        NaN
null               []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []  ...         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []         []
Make         \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n   \nAudi\n  ...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...  \nRena...

[20 rows x 15919 columns]

In [277]:
df.shape

(15919, 54)

In [278]:
df.size

859626

In [279]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat', 'km', 'registration', 'prev_owner', 'kW', 'hp', 'Type', 'Previous Owners', 'Next Inspection', 'Inspection new', 'Warranty', 'Full Service', 'Non-smoking Vehicle', 'null', 'Make', 'Model', 'Offer Number', 'First Registration', 'Body Color', 'Paint Type', 'Body Color Original', 'Upholstery', 'Body', 'Nr. of Doors', 'Nr. of Seats', 'Model Code', 'Gearing Type', 'Displacement', 'Cylinders', 'Weight', 'Drive chain', 'Fuel', 'Consumption', 'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n', '\nEntertainment & Media\n', '\nExtras\n', '\nSafety & Security\n', 'description', 'Emission Label', 'Gears', 'Country version', 'Electricity consumption', 'Last Service Date', 'Other Fuel Types', 'Availability', 'Last Timing Belt Service Date', 'Available from'], dtype='object')

In [280]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Dtype
---  ------                         -----
 0   url                            object
 1   make_model                     object
 2   short_description              object
 3   body_type                      object
 4   price                          int64
 5   vat                            object
 6   km                             object
 7   registration                   object
 8   prev_owner                     object
 9   kW                             float64
 10  hp                             object
 11  Type                           object
 12  Previous Owners                object
 13  Next Inspection                object
 14  Inspection new                 object
 15  Warranty                       object
 16  Full Service                   object
 17  Non-smoking Vehicle            object
 18  null                           object
 19  Make                           object
 20  Model                          object
 21  Offer Number                   object
 22  First Registration             object
 23  Body Color                     object
 24  Paint Type                     object
 25  Body Color Original            object
 26  Upholstery                     object
 27  Body                           object
 28  Nr. of Doors                   object
 29  Nr. of Seats                   object
 30  Model Code                     object
 31  Gearing Type                   object
 32  Displacement                   object
 33  Cylinders                      object
 34  Weight                         object
 35  Drive chain                    object
 36  Fuel                           object
 37  Consumption                    object
 38  CO2 Emission                   object
 39  Emission Class                 object
 40
Comfort & Convenience
        object
 41
Entertainment & Media
        object
 42
Extras
                       object
 43
Safety & Security
            object
 44  description                    object
 45  Emission Label                 object
 46  Gears                          object
 47  Country version                object
 48  Electricity consumption        object
 49  Last Service Date              object
 50  Other Fuel Types               object
 51  Availability                   object
 52  Last Timing Belt Service Date  object
 53  Available from                 object
dtypes: float64(1), int64(1), object(52)
memory usage: 6.6+ MB

In [281]:
df.dtypes.head()

url                  object
make_model           object
short_description    object
body_type            object
price                 int64
dtype: object

In [282]:
df.describe()

           price   kW
count  15919....  0.0
mean   18019....  NaN
std    7386.1...  NaN
min    13.000000  NaN
25%    12850....  NaN
50%    16900....  NaN
75%    21900....  NaN
max    74600....  NaN

In [283]:
# detect list columns
df.applymap(lambda x: isinstance(x, list)).all().head()

url                  False
make_model           False
short_description    False
body_type            False
price                False
dtype: bool

In [284]:
# detect dict columns
df.applymap(lambda x: isinstance(x, dict)).all().head()

url                  False
make_model           False
short_description    False
body_type            False
price                False
dtype: bool

In [285]:
# Detect missing values.Return a boolean same-sized object indicating if the values are NA.
df.isnull().sum()

url                                  0
make_model                           0
short_description                   46
body_type                           60
price                                0
vat                               4513
km                                   0
registration                         0
prev_owner                        6828
kW                               15919
hp                                   0
Type                                 2
Previous Owners                   6640
Next Inspection                  12384
Inspection new                   11987
Warranty                          5420
Full Service                      7704
Non-smoking Vehicle               8742
null                                 0
Make                                 0
Model                                0
Offer Number                      3175
First Registration                1597
Body Color                         597
Paint Type                        5772
Body Color Original               3759
Upholstery                        3720
Body                                60
Nr. of Doors                       212
Nr. of Seats                       977
Model Code                       10941
Gearing Type                         0
Displacement                       496
Cylinders                         5680
Weight                            6974
Drive chain                       6858
Fuel                                 0
Consumption                       1906
CO2 Emission                      1808
Emission Class                    3021
\nComfort & Convenience\n          920
\nEntertainment & Media\n         1374
\nExtras\n                        2962
\nSafety & Security\n              982
description                          0
Emission Label                   11934
Gears                             4712
Country version                   8333
Electricity consumption          15782
Last Service Date                15353
Other Fuel Types                 15039
Availability                     15284
Last Timing Belt Service Date    15903
Available from                   15647
dtype: int64

In [286]:
duplicate = df[df.duplicated("make_model")]   # ALT ALTA YAZILMIŞ DUBLİKASYON SATIR YOK GİBİ.
print("Duplicate Rows :")
duplicate.head(10)

Duplicate Rows :

          url make_model short_description  body_type  price        vat         km registration prev_owner  kW      hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
1   https:...    Audi A1  1.8 TF...            Sedans  14500  Price ...  80,000 km    03/2017         None NaN  141 kW  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, R...        NaN  ...    [\n4\n]    [\n058...  [\n, A...    [\n1,7...     [\n4\n]  [\n1,2...  [\nfro...   [\n, G...  [[5.6 ...   [\n129...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nLan...   [\n4 (...      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
2   https:...    Audi A1  Sportb...            Sedans  14640  VAT de...  83,450 km    02/2016    1 prev... NaN   85 kW  [, Use...      \n1\n             NaN             NaN      [\n, \...        NaN          NaN            []  \nAudi\n  [\n, A...  [\nAM-...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN  [\nfro...   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [MP3, ...                 [Alloy...  [ABS, ...             [\n, F...   [\n4 (...          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3   https:...    Audi A1  1.4 TD...            Sedans  14500       None  73,000 km    08/2016    1 prev... NaN   66 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,4...     [\n3\n]  [\n1,1...        NaN   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air s...                 [Bluet...                 [Alloy...  [ABS, ...             [\nAud...         NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4   https:...    Audi A1  Sportb...            Sedans  16790       None  16,200 km    05/2016    1 prev... NaN   66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\nC16...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]        NaN  [\nfro...   [\n, D...  [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, T...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
5   https:...    Audi A1  1.6 TD...            Sedans  15090       None  63,668 km    02/2016    1 prev... NaN   85 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\nJV0...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN        NaN   [\n, D...  [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nSic...   [\n4 (...          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
6   https:...    Audi A1  Sportb...         Statio...  16422  VAT de...  62,111 km    03/2016    1 prev... NaN   85 kW  [, Use...      \n1\n             NaN       [\nYes...            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\n200...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]        NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n98 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nRED...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
7   https:...    Audi A1  Sportb...           Compact  14480  VAT de...  14,986 km    02/2016    1 prev... NaN   66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...          NaN            []  \nAudi\n  [\n, A...  [\n183...    [\n, 2...          [\n, R...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...         NaN        NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [ABS, ...             [\n, A...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
8   https:...    Audi A1  SPB 1....            Sedans  16700       None  57,000 km    02/2016    1 prev... NaN   85 kW  [, Use...      \n1\n       [\n02/...             NaN      [\n12 ...        NaN          NaN            []  \nAudi\n  [\n, A...  [\n115...    [\n, 2...          [\n, G...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                   [Radio]                 [Alloy...  [ABS, ...             [\nAut...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
9   https:...    Audi A1  SPORTB...            Sedans  17990       None  16,103 km    06/2017         None NaN   70 kW  [, Use...        NaN             NaN             NaN      \n3 mo...        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, W...        NaN  ...    [\n4\n]          NaN  [\n, A...    [\n999...         NaN        NaN        NaN   [\n, G...        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN             [\nCli...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
10  https:...    Audi A1  SPORTB...            Sedans  18500  VAT de...  11,300 km    05/2018         None NaN   85 kW  [, Use...        NaN             NaN             NaN            NaN         \n          NaN            []  \nAudi\n  [\n, A...  [\n111...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [\n, D...  [[4 l/...   [\n105...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\naut...         NaN      [\n7\n]  [\nIta...             NaN                     NaN               NaN              NaN          NaN                           NaN

[10 rows x 54 columns]

In [287]:
null_columns=df.columns[df.isnull().any()]  # HANGİ SÜTUNLARDA NULL DĞERELERİNİN OLDUĞUNU GÖSTERİYOR.
null_columns

Index(['short_description', 'body_type', 'vat', 'prev_owner', 'kW', 'Type', 'Previous Owners', 'Next Inspection', 'Inspection new', 'Warranty', 'Full Service', 'Non-smoking Vehicle', 'Offer Number', 'First Registration', 'Body Color', 'Paint Type', 'Body Color Original', 'Upholstery', 'Body', 'Nr. of Doors', 'Nr. of Seats', 'Model Code', 'Displacement', 'Cylinders', 'Weight', 'Drive chain', 'Consumption', 'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n', '\nEntertainment & Media\n', '\nExtras\n', '\nSafety & Security\n', 'Emission Label', 'Gears', 'Country version', 'Electricity consumption', 'Last Service Date', 'Other Fuel Types', 'Availability', 'Last Timing Belt Service Date', 'Available from'], dtype='object')

In [288]:
df[df.isnull().any(axis=1)][null_columns].head()

  short_description body_type        vat prev_owner  kW       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle Offer Number First Registration Body Color Paint Type Body Color Original Upholstery       Body Nr. of Doors Nr. of Seats Model Code Displacement Cylinders     Weight Drive chain Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
0  Sportb...           Sedans  VAT de...  2 prev... NaN  [, Use...      \n2\n       [\n06/...       [\nYes...      [\n, \...   [\n, \n]     [\n, \n]           [\nLR-...    [\n, 2...          [\n, B...  [\nMet...  [\nMyt...           [\nClo...  [\n, S...    [\n5\n]      [\n5\n]    [\n058...  [\n1,4...     [\n3\n]  [\n1,2...  [\nfro...   [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
1  1.8 TF...           Sedans  Price ...       None NaN  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN                 NaN    [\n, 2...          [\n, R...        NaN        NaN           [\nClo...  [\n, S...    [\n3\n]      [\n4\n]    [\n058...  [\n1,7...     [\n4\n]  [\n1,2...  [\nfro...   [[5.6 ...   [\n129...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n4 (...      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
2  Sportb...           Sedans  VAT de...  1 prev... NaN  [, Use...      \n1\n             NaN             NaN      [\n, \...        NaN          NaN           [\nAM-...    [\n, 2...          [\n, B...  [\nMet...  [\nmyt...           [\nClo...  [\n, S...    [\n4\n]      [\n4\n]          NaN  [\n1,5...         NaN        NaN  [\nfro...   [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [MP3, ...                 [Alloy...  [ABS, ...             [\n4 (...          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3  1.4 TD...           Sedans       None  1 prev... NaN  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...                 NaN    [\n, 2...          [\n, B...  [\nMet...        NaN                 NaN  [\n, S...    [\n3\n]      [\n4\n]          NaN  [\n1,4...     [\n3\n]  [\n1,1...        NaN   [[3.8 ...   [\n99 ...    [\nEur...      [Air s...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4  Sportb...           Sedans       None  1 prev... NaN  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]           [\nC16...    [\n, 2...          [\n, B...  [\nMet...  [\nMyt...           [\nClo...  [\n, S...    [\n5\n]      [\n5\n]    [\n058...  [\n1,4...     [\n3\n]        NaN  [\nfro...   [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN

In [289]:
 df.isnull().head()

     url  make_model  short_description  body_type  price    vat     km  registration  prev_owner    kW     hp   Type  Previous Owners  Next Inspection  Inspection new  Warranty  Full Service  Non-smoking Vehicle   null   Make  Model  Offer Number  First Registration  Body Color  Paint Type  ...  Nr. of Seats  Model Code  Gearing Type  Displacement  Cylinders  Weight  Drive chain   Fuel  Consumption  CO2 Emission  Emission Class  \nComfort & Convenience\n  \nEntertainment & Media\n  \nExtras\n  \nSafety & Security\n  description  Emission Label  Gears  Country version  Electricity consumption  Last Service Date  Other Fuel Types  Availability  Last Timing Belt Service Date  Available from
0  False      False       False              False  False  False  False      False         False   True  False  False      False            False            False          False      False         False            False  False  False      False         False               False       False   ...      False         False       False         False         False   False      False    False      False        False         False           False                      False                      False       False                  False         True        True       True             True                     True               True              True          True                           True
1  False      False       False              False  False  False  False      False          True   True  False  False       True             True             True           True       True          True            False  False  False       True         False               False        True   ...      False         False       False         False         False   False      False    False      False        False         False           False                      False                      False       False                  False        False       False       True             True                     True               True              True          True                           True
2  False      False       False              False  False  False  False      False         False   True  False  False      False             True             True          False       True          True            False  False  False      False         False               False       False   ...      False          True       False         False          True    True      False    False      False        False         False           False                      False                      False       False                  False        False        True       True             True                     True               True              True          True                           True
3  False      False       False              False  False   True  False      False         False   True  False  False      False             True             True           True      False         False            False  False  False       True         False               False       False   ...      False          True       False         False         False   False       True    False      False        False         False           False                      False                      False       False                  False         True       False       True             True                     True               True              True          True                           True
4  False      False       False              False  False   True  False      False         False   True  False  False      False             True            False          False      False         False            False  False  False      False         False               False       False   ...      False         False       False         False         False    True      False    False      False        False         False           False                      False                      False       False                  False         True        True      False             True                     True               True              True          True                           True

[5 rows x 54 columns]

# 2. searchıng each rows

## 2.1.url

In [290]:
df["url"].head()

0    https:...
1    https:...
2    https:...
3    https:...
4    https:...
Name: url, dtype: object

In [291]:
df.url.isnull().sum()

0

In [292]:
df["url"].isnull().head()

0    False
1    False
2    False
3    False
4    False
Name: url, dtype: bool

In [293]:
df.url.value_counts(dropna=False).head()

https://www.autoscout24.com//offers/opel-corsa-e-1-2-selection-klima-esp-kopfairbag-zentralverrie-gasoline-white-9e765fb8-77c7-4529-aab5-a54fd41e2987    1
https://www.autoscout24.com//offers/opel-insignia-1-6-cdti-sportstounavi-applecarplay-eu6-diesel-black-f5be93f2-8d2b-4ec4-a9b5-e1c6ac4cf8ca              1
https://www.autoscout24.com//offers/opel-corsa-1-2-selection-klima-gasoline-blue-73651e97-821e-4857-8125-ba2df8a53754                                    1
https://www.autoscout24.com//offers/opel-insignia-1-6-cdti-sports-tourer-ecoflexstart-stop-edition-diesel-silver-a2306227-8b92-4a65-8e7e-cd89ec64f6a2    1
https://www.autoscout24.com//offers/opel-insignia-gand-sport-1-5-turbo-edition-gasoline-cffb3c8f-22a6-4485-88a6-0c60cdfae076                             1
Name: url, dtype: int64

In [294]:
df.url.value_counts().head()

https://www.autoscout24.com//offers/opel-corsa-e-1-2-selection-klima-esp-kopfairbag-zentralverrie-gasoline-white-9e765fb8-77c7-4529-aab5-a54fd41e2987    1
https://www.autoscout24.com//offers/opel-insignia-1-6-cdti-sportstounavi-applecarplay-eu6-diesel-black-f5be93f2-8d2b-4ec4-a9b5-e1c6ac4cf8ca              1
https://www.autoscout24.com//offers/opel-corsa-1-2-selection-klima-gasoline-blue-73651e97-821e-4857-8125-ba2df8a53754                                    1
https://www.autoscout24.com//offers/opel-insignia-1-6-cdti-sports-tourer-ecoflexstart-stop-edition-diesel-silver-a2306227-8b92-4a65-8e7e-cd89ec64f6a2    1
https://www.autoscout24.com//offers/opel-insignia-gand-sport-1-5-turbo-edition-gasoline-cffb3c8f-22a6-4485-88a6-0c60cdfae076                             1
Name: url, dtype: int64

## 2.2.make_model

In [295]:
df["make_model"].head()

0    Audi A1
1    Audi A1
2    Audi A1
3    Audi A1
4    Audi A1
Name: make_model, dtype: object

In [ ]:
df["make_model"].head()

In [296]:
df.make_model.isnull().sum()

0

In [297]:
df.make_model.isnull().head()

0    False
1    False
2    False
3    False
4    False
Name: make_model, dtype: bool

In [298]:
df.make_model.value_counts(dropna=False).head()

Audi A3          3097
Audi A1          2614
Opel Insignia    2598
Opel Astra       2526
Opel Corsa       2219
Name: make_model, dtype: int64

In [299]:
df.make_model.value_counts().head()

Audi A3          3097
Audi A1          2614
Opel Insignia    2598
Opel Astra       2526
Opel Corsa       2219
Name: make_model, dtype: int64

In [300]:
df.duplicated("make_model").sum()

15910

In [301]:
df.duplicated("make_model").sum()  # 9 rakam nerede?

15910

In [4]:
df[~df.duplicated("make_model")]    ??

             url make_model short_description  body_type  price        vat         km registration prev_owner  kW      hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null       Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
0      https:...    Audi A1  Sportb...            Sedans  15770  VAT de...  56,013 km    01/2016    2 prev... NaN   66 kW  [, Use...      \n2\n       [\n06/...       [\nYes...      [\n, \...   [\n, \n]     [\n, \n]            []   \nAudi\n  [\n, A...  [\nLR-...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]  [\n1,2...  [\nfro...   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, S...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
2614   https:...    Audi A2  30 TDI...          Off-Road  28200  VAT de...  26,166 km    10/2018    1 prev... NaN   85 kW  [, Emp...      \n1\n       [\n10/...             NaN      [\n, \...   [\n, \n]     [\n, \n]            []   \nAudi\n  [\n, A...  [\n276...    [\n, 2...          [\n, G...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, M...    [\n1,5...         NaN        NaN  [\nfro...   [\n, D...  [[4.9 ...         NaN    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, T...   [\n4 (...          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
2615   https:...    Audi A3  1,5 TF...         Conver...  10893  VAT de...  19,800 km    06/2018         None NaN  110 kW  [, Use...        NaN             NaN             NaN      [\n16 ...  [\n, \...     [\n, \n]            []   \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, R...        NaN  ...    [\n4\n]          NaN  [\n, A...    [\n1,4...     [\n4\n]  [\n1,4...  [\nfro...   [\n, G...  [[5.1 ...   [\n116...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, A...         NaN      [\n7\n]  [\nIta...             NaN               \n06/2...               NaN              NaN          NaN                           NaN
5712   https:...  Opel A...  Editio...         Statio...   6000       None  260,00...    05/2016    1 prev... NaN  100 kW  [, Use...      \n1\n       [\n05/...             NaN            NaN        NaN          NaN            []   \nOpel\n  [\n, A...        NaN    [\n, 2...          [\n, S...  [\nMet...  ...    [\n5\n]    [\n003...  [\n, A...    [\n1,5...     [\n4\n]  [\n1,4...        NaN   [\n, D...  [[4.5 ...   [\n119...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n(((...   [\n4 (...      [\n6\n]  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
8238   https:...  Opel C...  1.4 90...            Sedans   7700       None  100,00...    03/2016    1 prev... NaN   66 kW  [, Use...      \n1\n             NaN             NaN      [\n12 ...  [\n, \...     [\n, \n]            []   \nOpel\n  [\n, C...        NaN    [\n, 2...          [\n, S...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,3...     [\n4\n]  [\n1,1...  [\nfro...   [\n, G...  [[4.7 ...   [\n110...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n---...         NaN      [\n6\n]  [\nIta...             NaN                     NaN               NaN              NaN          NaN                           NaN
10457  https:...  Opel I...  ST 1.6...         Statio...   8980  VAT de...  174,56...    05/2016    1 prev... NaN  100 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...          NaN            []   \nOpel\n  [\n, I...  [\n226...    [\n, 2...          [\n, B...        NaN  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN        NaN   [\n, D...        NaN         NaN    [[], [...      [Air c...                 [CD pl...                 [Roof ...  [ABS, ...             [\n, N...   [\n4 (...          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
13055  https:...  Renaul...  Experi...           Compact   7650  VAT de...  161,55...    04/2016    1 prev... NaN   66 kW  [, Use...      \n1\n       [\n04/...             NaN            NaN  [\n, \...     [\n, \n]            []  \nRena...  [\n, C...        NaN    [\n, 2...          [\n, W...        NaN  ...    [\n5\n]    [\n333...  [\n, A...    [\n1,4...         NaN        NaN        NaN   [\n, D...  [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, Z...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
14894  https:...  Renaul...  Deluxe...          Off-Road  13250       None       - km        -/-         None NaN    - kW  [, New...        NaN             NaN             NaN      \n12 m...        NaN          NaN            []  \nRena...  [\n, D...  [\n223...          NaN          [\n, B...        NaN  ...    [\n5\n]          NaN  [\n, A...    [\n1,9...     [\n4\n]        NaN        NaN   [\n, G...  [[10 l...   [\n150...    [\nEur...      [Air c...                 [Bluet...                       NaN  [ABS, ...             [\n- E...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
14928  https:...  Renaul...  Zen En...              None  17500       None  141,00...    05/2016         None NaN  118 kW  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN            []  \nRena...  [\n, E...        NaN    [\n, 2...          [\n, W...        NaN  ...        NaN          NaN  [\n, A...          NaN         NaN        NaN        NaN   [\n, D...  [[4.6 ...   [\n120...          NaN      [Air c...                       NaN                       NaN  [ABS, ...             [\nMás...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[9 rows x 54 columns]

## 2.3. short_description

In [302]:
df.short_description.head()

0    Sportb...
1    1.8 TF...
2    Sportb...
3    1.4 TD...
4    Sportb...
Name: short_description, dtype: object

In [303]:
df.short_description.isnull().sum()

46

In [304]:
null_columns=df.columns[df.isnull().any()]
df[df["short_description"].isnull()][null_columns].head()

     short_description  body_type        vat prev_owner  kW       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle Offer Number First Registration Body Color Paint Type Body Color Original Upholstery       Body Nr. of Doors Nr. of Seats Model Code Displacement Cylinders Weight Drive chain Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n Emission Label Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
372        None           Compact       None       None NaN  [, Use...        NaN             NaN         \nYes\n            NaN        NaN    [\n, \...                 NaN    [\n, 2...          [\n, R...  [\nMet...  [\nMis...           [\nPar...  [\n, C...    [\n2\n]      [\n4\n]          NaN  [\n1,3...         NaN    NaN        NaN   [[5.1 ...   [\n117...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n4 (...       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
503        None            Sedans  Price ...  2 prev... NaN  [, Use...      \n2\n       [\n04/...             NaN            NaN        NaN     [\n, \n]                 NaN    [\n, 2...          [\n, V...        NaN        NaN                 NaN  [\n, S...    [\n5\n]      [\n4\n]          NaN  [\n1,4...         NaN    NaN        NaN         NaN         NaN    [[], [...      [Armre...                 [Bluet...                       NaN  [Tire ...             [\n4 (...       NaN        NaN             NaN               [\n11/...               NaN              NaN          NaN                           NaN
2665       None         Statio...       None  1 prev... NaN  [, Use...      \n1\n       [\n06/...             NaN            NaN   [\n, \n]          NaN                 NaN    [\n, 2...          [\n, G...  [\nMet...        NaN           [\nClo...  [\n, S...    [\n5\n]      [\n5\n]          NaN        NaN         NaN    NaN        NaN         NaN         NaN    [[], [...      [Light...                 [Bluet...                 [Sport...  [ABS, ...             [\n4 (...       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
2790       None         Statio...       None  1 prev... NaN  [, Use...      \n1\n             NaN             NaN      [\n12 ...        NaN          NaN           [\n162...    [\n, 2...          [\n, W...  [\nMet...        NaN           [\nClo...  [\n, S...    [\n5\n]      [\n5\n]          NaN        NaN         NaN    NaN        NaN         NaN         NaN          NaN      [Air c...                       NaN                 [Alloy...  [ABS, ...                   NaN       NaN  [\nSpa...             NaN                     NaN               NaN              NaN          NaN                           NaN
2996       None         Statio...  VAT de...  1 prev... NaN  [, Use...      \n1\n             NaN       [\nYes...            NaN   [\n, \n]     [\n, \n]                 NaN    [\n, 2...          [\n, S...  [\nMet...        NaN           [\nClo...  [\n, S...    [\n4\n]      [\n5\n]          NaN  [\n1,9...         NaN    NaN        NaN         NaN         NaN    [[], [...      [Air c...                 [Bluet...                       NaN  [ABS, ...             [\n4 (...       NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN

In [305]:
df.short_description.isnull().head(372-379)

0        False
1        False
2        False
3        False
4        False
         ...
15907    False
15908    False
15909    False
15910    False
15911    False
Name: short_description, Length: 15912, dtype: bool

In [306]:
df.short_description.value_counts(dropna=False).head()

SPB 1.6 TDI 116 CV S tronic Sport        64
NaN                                      46
1.4 66kW (90CV) Selective                40
MOVE KLIMA CD USB ALLWETTER BLUETOOTH    38
SPB 30 TFSI S tronic Admired             35
Name: short_description, dtype: int64

In [307]:
df.duplicated("short_description").value_counts()  # There are 5917 each duplicated rows and these rows should be unique.

False    10002
True      5917
dtype: int64

In [308]:
df.duplicated("short_description", keep='first').head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [309]:
df.duplicated(subset=['short_description']).head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [310]:
df.drop_duplicates(subset=['short_description']).head()

         url make_model short_description body_type  price        vat         km registration prev_owner  kW      hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
0  https:...    Audi A1  Sportb...           Sedans  15770  VAT de...  56,013 km    01/2016    2 prev... NaN   66 kW  [, Use...      \n2\n       [\n06/...       [\nYes...      [\n, \...   [\n, \n]     [\n, \n]            []  \nAudi\n  [\n, A...  [\nLR-...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]  [\n1,2...  [\nfro...   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, S...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
1  https:...    Audi A1  1.8 TF...           Sedans  14500  Price ...  80,000 km    03/2017         None NaN  141 kW  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, R...        NaN  ...    [\n4\n]    [\n058...  [\n, A...    [\n1,7...     [\n4\n]  [\n1,2...  [\nfro...   [\n, G...  [[5.6 ...   [\n129...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nLan...   [\n4 (...      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
2  https:...    Audi A1  Sportb...           Sedans  14640  VAT de...  83,450 km    02/2016    1 prev... NaN   85 kW  [, Use...      \n1\n             NaN             NaN      [\n, \...        NaN          NaN            []  \nAudi\n  [\n, A...  [\nAM-...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN  [\nfro...   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [MP3, ...                 [Alloy...  [ABS, ...             [\n, F...   [\n4 (...          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3  https:...    Audi A1  1.4 TD...           Sedans  14500       None  73,000 km    08/2016    1 prev... NaN   66 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,4...     [\n3\n]  [\n1,1...        NaN   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air s...                 [Bluet...                 [Alloy...  [ABS, ...             [\nAud...         NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4  https:...    Audi A1  Sportb...           Sedans  16790       None  16,200 km    05/2016    1 prev... NaN   66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\nC16...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]        NaN  [\nfro...   [\n, D...  [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, T...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN

[5 rows x 54 columns]

In [311]:
df["short_description"].shape

(15919,)

In [312]:
## to extract the unique values from a dataset we can use the “~” (tilda) symbol to negate the values. UNIQUE VERİLERİ GÖRMEK İÇİN

df_unique~df["Employee_Name"].duplicated(keep=False)df[df_unique]

SyntaxError: invalid syntax (<ipython-input-312-422f15203973>, line 3)

## 2.4. body_type

In [6]:
df.body_type.head()

0    Sedans
1    Sedans
2    Sedans
3    Sedans
4    Sedans
Name: body_type, dtype: object

In [7]:
df.body_type.isnull().sum()

60

In [10]:
null_columns=df.columns[df.isnull().any()]
df[df["body_type"].isnull()][null_columns].head()

     short_description body_type        vat prev_owner  kW       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle Offer Number First Registration Body Color Paint Type Body Color Original Upholstery Body Nr. of Doors Nr. of Seats Model Code Displacement Cylinders     Weight Drive chain Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
3175    1.6 TDi             None       None  1 prev... NaN  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...                 NaN    [\n, 2...          [\n, B...  [\nMet...        NaN           [\nClo...  NaN    [\n5\n]      [\n5\n]          NaN  [\n1,5...     [\n4\n]  [\n1,3...        NaN   [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3255  1.6 TD...             None  Price ...       None NaN  [, Use...        NaN       \n07/2...             NaN            NaN  [\n, \...    [\n, \...                 NaN    [\n, 2...          [\n, W...        NaN        NaN           [\nClo...  NaN    [\n3\n]      [\n5\n]          NaN  [\n1,5...     [\n4\n]  [\n1,2...        NaN   [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3975  Sportb...             None       None  2 prev... NaN  [, Use...      \n2\n       [\n03/...             NaN      [\n, \...   [\n, \n]     [\n, \n]                 NaN    [\n, 2...          [\n, B...  [\nMet...        NaN                 NaN  NaN    [\n5\n]      [\n5\n]          NaN  [\n999...     [\n3\n]  [\n1,2...        NaN   [[4.7 ...   [\n107...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3997  (3E GE...             None  VAT de...  1 prev... NaN  [, Use...      \n1\n             NaN             NaN      [\n6 m...   [\n, \n]          NaN           [\n191...    [\n, 2...          [\n, B...        NaN  [\nNOI...                 NaN  NaN    [\n3\n]          NaN          NaN  [\n1,5...         NaN        NaN        NaN         NaN         NaN          NaN      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4206  Sportb...             None       None       None NaN  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN                 NaN    [\n, 2...          [\n, W...        NaN        NaN                 NaN  NaN    [\n5\n]          NaN          NaN        NaN         NaN        NaN        NaN   [[5.1 ...   [\n117...          NaN      [Air c...                       NaN                       NaN  [ABS, ...                   NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

In [11]:
df[df["body_type"].isnull()].head() # BODY_TYPE SÜTUNUNDAKİ "NONE" DEĞERLERİ GÖSTERİR.

            url make_model short_description body_type  price        vat         km registration prev_owner  kW     hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
3175  https:...    Audi A3    1.6 TDi             None  14400       None  119,00...    08/2016    1 prev... NaN  81 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]          NaN  [\n, M...    [\n1,5...     [\n4\n]  [\n1,3...        NaN   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nAud...         NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3255  https:...    Audi A3  1.6 TD...             None  18500  Price ...  70,000 km    07/2016         None NaN  81 kW  [, Use...        NaN       \n07/2...             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, W...        NaN  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...        NaN   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nmod...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3975  https:...    Audi A3  Sportb...             None  19950       None  25,000 km    03/2017    2 prev... NaN  85 kW  [, Use...      \n2\n       [\n03/...             NaN      [\n, \...   [\n, \n]     [\n, \n]            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n999...     [\n3\n]  [\n1,2...        NaN   [\n, G...  [[4.7 ...   [\n107...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nAns...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3997  https:...    Audi A3  (3E GE...             None  19750  VAT de...  38,800 km    02/2017    1 prev... NaN  82 kW  [, Use...      \n1\n             NaN             NaN      [\n6 m...   [\n, \n]          NaN            []  \nAudi\n  [\n, A...  [\n191...    [\n, 2...          [\n, B...        NaN  ...        NaN          NaN  [\n, A...    [\n1,5...         NaN        NaN        NaN   [\n, D...        NaN         NaN          NaN      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n5 p...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4206  https:...    Audi A3  Sportb...             None  18490       None  20,000 km    12/2017         None NaN  92 kW  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, W...        NaN  ...        NaN          NaN  [\n, M...          NaN         NaN        NaN        NaN   [\n, G...  [[5.1 ...   [\n117...          NaN      [Air c...                       NaN                       NaN  [ABS, ...             [\nMás...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[5 rows x 54 columns]

In [15]:
df['body_type']= df['body_type'].replace(to_replace=np.nan, value= "Unknown") # BURDA BİR YANLIŞLIK OLDU.
df['body_type'].head()

0    Sedans
1    Sedans
2    Sedans
3    Sedans
4    Sedans
Name: body_type, dtype: object

In [16]:
df["body_type"].value_counts(dropna=False)  # BURDA BİR YANLIŞLIK OLDU.

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
Unknown            60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [ ]:
df.body_type.isnull().to_frame().head()

   body_type
0      False
1      False
2      False
3      False
4      False

In [ ]:

df['body_type'].value_counts(dropna=False).to_frame().head() # BURDA BİR YANLIŞKLIK VAR.

                                                                                                                                                       body_type
https://www.autoscout24.com//offers/opel-corsa-e-1-2-selection-klima-esp-kopfairbag-zentralverrie-gasoline-white-9e765fb8-77c7-4529-aab5-a54fd41e2987          1
https://www.autoscout24.com//offers/opel-insignia-1-6-cdti-sportstounavi-applecarplay-eu6-diesel-black-f5be93f2-8d2b-4ec4-a9b5-e1c6ac4cf8ca                    1
https://www.autoscout24.com//offers/opel-corsa-1-2-selection-klima-gasoline-blue-73651e97-821e-4857-8125-ba2df8a53754                                          1
https://www.autoscout24.com//offers/opel-insignia-1-6-cdti-sports-tourer-ecoflexstart-stop-edition-diesel-silver-a2306227-8b92-4a65-8e7e-cd89ec64f6a2          1
https://www.autoscout24.com//offers/opel-insignia-gand-sport-1-5-turbo-edition-gasoline-cffb3c8f-22a6-4485-88a6-0c60cdfae076                                   1

In [ ]:
# value_counts percentage view

df['body_type'].value_counts(normalize=True, dropna=False).to_frame().head()

                                                                                                                                                       body_type
https://www.autoscout24.com//offers/opel-corsa-e-1-2-selection-klima-esp-kopfairbag-zentralverrie-gasoline-white-9e765fb8-77c7-4529-aab5-a54fd41e2987   0.000063
https://www.autoscout24.com//offers/opel-insignia-1-6-cdti-sportstounavi-applecarplay-eu6-diesel-black-f5be93f2-8d2b-4ec4-a9b5-e1c6ac4cf8ca             0.000063
https://www.autoscout24.com//offers/opel-corsa-1-2-selection-klima-gasoline-blue-73651e97-821e-4857-8125-ba2df8a53754                                   0.000063
https://www.autoscout24.com//offers/opel-insignia-1-6-cdti-sports-tourer-ecoflexstart-stop-edition-diesel-silver-a2306227-8b92-4a65-8e7e-cd89ec64f6a2   0.000063
https://www.autoscout24.com//offers/opel-insignia-gand-sport-1-5-turbo-edition-gasoline-cffb3c8f-22a6-4485-88a6-0c60cdfae076                            0.000063

In [ ]:
df.duplicated("body_type").value_counts().to_frame()  # There are 10 each duplicated rows and these rows should be unique.

           0
True   15909
False     10

In [ ]:
df[df.duplicated("body_type", keep='first').to_frame()].head()

   url make_model short_description body_type  price  vat   km registration prev_owner  kW   hp Type Previous Owners Next Inspection Inspection new Warranty Full Service Non-smoking Vehicle null Make Model Offer Number First Registration Body Color Paint Type Body Color Original Upholstery Body Nr. of Doors Nr. of Seats Model Code Gearing Type Displacement Cylinders Weight Drive chain Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
0  NaN        NaN               NaN       NaN    NaN  NaN  NaN          NaN        NaN NaN  NaN  NaN             NaN             NaN            NaN      NaN          NaN                 NaN  NaN  NaN   NaN          NaN                NaN        NaN        NaN                 NaN        NaN  NaN          NaN          NaN        NaN          NaN          NaN       NaN    NaN         NaN  NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN            NaN   NaN             NaN                     NaN               NaN              NaN          NaN                           NaN            NaN
1  NaN        NaN               NaN       NaN    NaN  NaN  NaN          NaN        NaN NaN  NaN  NaN             NaN             NaN            NaN      NaN          NaN                 NaN  NaN  NaN   NaN          NaN                NaN        NaN        NaN                 NaN        NaN  NaN          NaN          NaN        NaN          NaN          NaN       NaN    NaN         NaN  NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN            NaN   NaN             NaN                     NaN               NaN              NaN          NaN                           NaN            NaN
2  NaN        NaN               NaN       NaN    NaN  NaN  NaN          NaN        NaN NaN  NaN  NaN             NaN             NaN            NaN      NaN          NaN                 NaN  NaN  NaN   NaN          NaN                NaN        NaN        NaN                 NaN        NaN  NaN          NaN          NaN        NaN          NaN          NaN       NaN    NaN         NaN  NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN            NaN   NaN             NaN                     NaN               NaN              NaN          NaN                           NaN            NaN
3  NaN        NaN               NaN       NaN    NaN  NaN  NaN          NaN        NaN NaN  NaN  NaN             NaN             NaN            NaN      NaN          NaN                 NaN  NaN  NaN   NaN          NaN                NaN        NaN        NaN                 NaN        NaN  NaN          NaN          NaN        NaN          NaN          NaN       NaN    NaN         NaN  NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN            NaN   NaN             NaN                     NaN               NaN              NaN          NaN                           NaN            NaN
4  NaN        NaN               NaN       NaN    NaN  NaN  NaN          NaN        NaN NaN  NaN  NaN             NaN             NaN            NaN      NaN          NaN                 NaN  NaN  NaN   NaN          NaN                NaN        NaN        NaN                 NaN        NaN  NaN          NaN          NaN        NaN          NaN          NaN       NaN    NaN         NaN  NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN            NaN   NaN             NaN                     NaN               NaN              NaN          NaN                           NaN            NaN

In [ ]:
duplicate = df[df.duplicated("body_type")]   # ALT ALTA YAZILMIŞ DUBLİKASYON SATIR YOK GİBİ.
print("Duplicate Rows :")
duplicate

Duplicate Rows :

In [ ]:
df[df["body_type"].duplicated()].head() # DUBLİKASYON SÜTUNLARI GÖSTERİR.

Empty DataFrame
Columns: [url, make_model, short_description, body_type, price, vat, km, registration, prev_owner, kW, hp, Type, Previous Owners, Next Inspection, Inspection new, Warranty, Full Service, Non-smoking Vehicle, null, Make, Model, Offer Number, First Registration, Body Color, Paint Type, Body Color Original, Upholstery, Body, Nr. of Doors, Nr. of Seats, Model Code, Gearing Type, Displacement, Cylinders, Weight, Drive chain, Fuel, Consumption, CO2 Emission, Emission Class,
Comfort & Convenience
,
Entertainment & Media
,
Extras
,
Safety & Security
, description, Emission Label, Gears, Country version, Electricity consumption, Last Service Date, Other Fuel Types, Availability, Last Timing Belt Service Date, Available from]
Index: []

[0 rows x 54 columns]

## 2.5.price

In [ ]:
df["price"].head()

0    15770
1    14500
2    14640
3    14500
4    16790
Name: price, dtype: int64

In [ ]:
df.price.isnull().sum()

0

In [ ]:
null_columns=df.columns[df.isnull().any()]
df[df["price"].isnull()][null_columns].head()

Empty DataFrame
Columns: [short_description, vat, prev_owner, kW, Type, Previous Owners, Next Inspection, Inspection new, Warranty, Full Service, Non-smoking Vehicle, Offer Number, First Registration, Body Color, Paint Type, Body Color Original, Upholstery, Body, Nr. of Doors, Nr. of Seats, Model Code, Displacement, Cylinders, Weight, Drive chain, Consumption, CO2 Emission, Emission Class,
Comfort & Convenience
,
Entertainment & Media
,
Extras
,
Safety & Security
, Emission Label, Gears, Country version, Electricity consumption, Last Service Date, Other Fuel Types, Availability, Last Timing Belt Service Date, Available from]
Index: []

In [ ]:
df.price.isnull().to_frame().head()

   price
0  False
1  False
2  False
3  False
4  False

In [ ]:
df['price'].value_counts(dropna=False).to_frame().head()

       price
14990    154
15990    151
10990    139
15900    106
17990    102

In [ ]:
# value_counts percentage view

df['price'].value_counts(normalize=True, dropna=False).to_frame().head()

          price
14990  0.009674
15990  0.009486
10990  0.008732
15900  0.006659
17990  0.006407

In [ ]:
df.duplicated("price").value_counts().to_frame()  # There are 10 each duplicated rows and these rows should be unique.

           0
True   12963
False   2956

In [ ]:
df[df.duplicated("body_type", keep='first').to_frame()]

In [ ]:
df[df["body_type"].duplicated()].head() # DUBLİKASYON SÜTUNLARI GÖSTERİR.

In [ ]:
duplicate = df[df.duplicated("body_type")]   # ALT ALTA YAZILMIŞ DUBLİKASYON SATIR YOK GİBİ.
print("Duplicate Rows :")
duplicate

## 2.6.vat

In [ ]:
df.vat.head()

0    VAT de...
1    Price ...
2    VAT de...
3         None
4         None
Name: vat, dtype: object

In [ ]:
df.vat.isnull().sum()

4513

In [ ]:
df[df["vat"].isnull()].head() # BODY_TYPE SÜTUNUNDAKİ "NONE" DEĞERLERİ GÖSTERİR.

         url make_model short_description  body_type  price   vat         km registration prev_owner  kW     hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
3  https:...    Audi A1  1.4 TD...         https:...  14500  None  73,000 km    08/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,4...     [\n3\n]  [\n1,1...        NaN   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air s...                 [Bluet...                 [Alloy...  [ABS, ...             [\nAud...         NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4  https:...    Audi A1  Sportb...         https:...  16790  None  16,200 km    05/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\nC16...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]        NaN  [\nfro...   [\n, D...  [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, T...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
5  https:...    Audi A1  1.6 TD...         https:...  15090  None  63,668 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\nJV0...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN        NaN   [\n, D...  [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nSic...   [\n4 (...          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
8  https:...    Audi A1  SPB 1....         https:...  16700  None  57,000 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n       [\n02/...             NaN      [\n12 ...        NaN          NaN            []  \nAudi\n  [\n, A...  [\n115...    [\n, 2...          [\n, G...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                   [Radio]                 [Alloy...  [ABS, ...             [\nAut...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
9  https:...    Audi A1  SPORTB...         https:...  17990  None  16,103 km    06/2017         None NaN  70 kW  [, Use...        NaN             NaN             NaN      \n3 mo...        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, W...        NaN  ...    [\n4\n]          NaN  [\n, A...    [\n999...         NaN        NaN        NaN   [\n, G...        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN             [\nCli...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[5 rows x 54 columns]

In [ ]:
null_columns=df.columns[df.isnull().any()]
df[df["vat"].isnull()][null_columns].head()

  short_description   vat prev_owner  kW       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle Offer Number First Registration Body Color Paint Type Body Color Original Upholstery       Body Nr. of Doors Nr. of Seats Model Code Displacement Cylinders     Weight Drive chain Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
3  1.4 TD...         None  1 prev... NaN  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...                 NaN    [\n, 2...          [\n, B...  [\nMet...        NaN                 NaN  [\n, S...    [\n3\n]      [\n4\n]          NaN  [\n1,4...     [\n3\n]  [\n1,1...        NaN   [[3.8 ...   [\n99 ...    [\nEur...      [Air s...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4  Sportb...         None  1 prev... NaN  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]           [\nC16...    [\n, 2...          [\n, B...  [\nMet...  [\nMyt...           [\nClo...  [\n, S...    [\n5\n]      [\n5\n]    [\n058...  [\n1,4...     [\n3\n]        NaN  [\nfro...   [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
5  1.6 TD...         None  1 prev... NaN  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...           [\nJV0...    [\n, 2...          [\n, W...  [\nMet...        NaN           [\nPar...  [\n, S...    [\n4\n]      [\n5\n]          NaN  [\n1,5...         NaN        NaN        NaN   [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n4 (...          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
8  SPB 1....         None  1 prev... NaN  [, Use...      \n1\n       [\n02/...             NaN      [\n12 ...        NaN          NaN           [\n115...    [\n, 2...          [\n, G...  [\nMet...  [\nGri...           [\nClo...  [\n, S...    [\n5\n]      [\n4\n]          NaN  [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                   [Radio]                 [Alloy...  [ABS, ...                   NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
9  SPORTB...         None       None NaN  [, Use...        NaN             NaN             NaN      \n3 mo...        NaN          NaN                 NaN    [\n, 2...          [\n, W...        NaN  [\nBla...                 NaN  [\n, S...    [\n5\n]      [\n4\n]          NaN  [\n999...         NaN        NaN        NaN         NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

In [ ]:
df.vat.isnull().head()

0    False
1    False
2    False
3     True
4     True
Name: vat, dtype: bool

In [ ]:
df.vat.isnull().to_frame().head()

     vat
0  False
1  False
2  False
3   True
4   True

In [ ]:
df['vat'].value_counts(dropna=False).to_frame()

              vat
VAT ded...  10980
NaN          4513
Price n...    426

In [ ]:
# value_counts percentage view

df['vat'].value_counts(normalize=True, dropna=False).to_frame()

                 vat
VAT ded...  0.689742
NaN         0.283498
Price n...  0.026760

In [ ]:
df.duplicated("vat").value_counts().to_frame()  # There are 10 each duplicated rows and these rows should be unique.

           0
True   15916
False      3

In [ ]:
df[df.duplicated("vat", keep='first').to_frame()]

       url make_model short_description body_type  price  vat   km registration prev_owner  kW   hp Type Previous Owners Next Inspection Inspection new Warranty Full Service Non-smoking Vehicle null Make Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders Weight Drive chain Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
0      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
1      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
2      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
...    ...        ...        ...              ...    ...  ...  ...        ...          ...  ..  ...  ...        ...             ...             ...          ...        ...          ...           ...  ...   ...        ...          ...                ...        ...  ...        ...          ...        ...          ...         ...    ...        ...   ...        ...         ...          ...            ...                       ...                       ...        ...                   ...         ...       ...        ...             ...                     ...               ...              ...          ...                           ...
15914  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
15915  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
15916  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
15917  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
15918  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[15919 rows x 54 columns]

In [ ]:
df[df["vat"].duplicated()].head() # DUBLİKASYON SÜTUNLARI GÖSTERİR.

         url make_model short_description  body_type  price        vat         km registration prev_owner  kW     hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
2  https:...    Audi A1  Sportb...         https:...  14640  VAT de...  83,450 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN             NaN      [\n, \...        NaN          NaN            []  \nAudi\n  [\n, A...  [\nAM-...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...         NaN    NaN  [\nfro...   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [MP3, ...                 [Alloy...  [ABS, ...             [\n, F...   [\n4 (...          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4  https:...    Audi A1  Sportb...         https:...  16790       None  16,200 km    05/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\nC16...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]    NaN  [\nfro...   [\n, D...  [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, T...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
5  https:...    Audi A1  1.6 TD...         https:...  15090       None  63,668 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\nJV0...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...         NaN    NaN        NaN   [\n, D...  [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nSic...   [\n4 (...          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
6  https:...    Audi A1  Sportb...         https:...  16422  VAT de...  62,111 km    03/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN       [\nYes...            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\n200...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]    NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n98 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nRED...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
7  https:...    Audi A1  Sportb...         https:...  14480  VAT de...  14,986 km    02/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...          NaN            []  \nAudi\n  [\n, A...  [\n183...    [\n, 2...          [\n, R...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...         NaN    NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [ABS, ...             [\n, A...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[5 rows x 54 columns]

In [ ]:
duplicate = df[df.duplicated("vat")]   # ALT ALTA YAZILMIŞ DUBLİKASYON SATIR YOK GİBİ.
print("Duplicate Rows :")
duplicate.head(10)

Duplicate Rows :

          url make_model short_description  body_type  price        vat         km registration prev_owner  kW     hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
2   https:...    Audi A1  Sportb...         https:...  14640  VAT de...  83,450 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN             NaN      [\n, \...        NaN          NaN            []  \nAudi\n  [\n, A...  [\nAM-...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN  [\nfro...   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [MP3, ...                 [Alloy...  [ABS, ...             [\n, F...   [\n4 (...          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4   https:...    Audi A1  Sportb...         https:...  16790       None  16,200 km    05/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\nC16...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]        NaN  [\nfro...   [\n, D...  [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, T...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
5   https:...    Audi A1  1.6 TD...         https:...  15090       None  63,668 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\nJV0...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN        NaN   [\n, D...  [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nSic...   [\n4 (...          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
6   https:...    Audi A1  Sportb...         https:...  16422  VAT de...  62,111 km    03/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN       [\nYes...            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\n200...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]        NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n98 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nRED...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
7   https:...    Audi A1  Sportb...         https:...  14480  VAT de...  14,986 km    02/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...          NaN            []  \nAudi\n  [\n, A...  [\n183...    [\n, 2...          [\n, R...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...         NaN        NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [ABS, ...             [\n, A...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
8   https:...    Audi A1  SPB 1....         https:...  16700       None  57,000 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n       [\n02/...             NaN      [\n12 ...        NaN          NaN            []  \nAudi\n  [\n, A...  [\n115...    [\n, 2...          [\n, G...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                   [Radio]                 [Alloy...  [ABS, ...             [\nAut...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
9   https:...    Audi A1  SPORTB...         https:...  17990       None  16,103 km    06/2017         None NaN  70 kW  [, Use...        NaN             NaN             NaN      \n3 mo...        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, W...        NaN  ...    [\n4\n]          NaN  [\n, A...    [\n999...         NaN        NaN        NaN   [\n, G...        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN             [\nCli...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
10  https:...    Audi A1  SPORTB...         https:...  18500  VAT de...  11,300 km    05/2018         None NaN  85 kW  [, Use...        NaN             NaN             NaN            NaN         \n          NaN            []  \nAudi\n  [\n, A...  [\n111...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [\n, D...  [[4 l/...   [\n105...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\naut...         NaN      [\n7\n]  [\nIta...             NaN                     NaN               NaN              NaN          NaN                           NaN
11  https:...    Audi A1  Sportb...         https:...  17990       None  26,415 km    05/2016    1 prev... NaN  92 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\n125...    [\n, 2...          [\n, S...  [\nUni...  ...        NaN    [\n058...  [\n, A...    [\n1,3...     [\n4\n]        NaN  [\nfro...   [\n, S...  [[4.9 ...   [\n112...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [ABS, ...             [\n, A...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
12  https:...    Audi A1  Sportb...         https:...  18380       None  31,600 km    09/2016    1 prev... NaN  92 kW  [, Use...      \n1\n       [\n09/...             NaN      [\n, \...        NaN    [\n, \...            []  \nAudi\n  [\n, A...  [\n86G...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,3...     [\n4\n]        NaN  [\nfro...   [\n, R...  [[4.9 ...   [\n112...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, H...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN

[10 rows x 54 columns]

## 2.7. km

In [ ]:
df.body_type.isnull().sum()

In [ ]:
df[df["body_type"].isnull()].head() # BODY_TYPE SÜTUNUNDAKİ "NONE" DEĞERLERİ GÖSTERİR.

In [ ]:
df.body_type.isnull().to_frame().head()

## 2.8.registration

2.9.prev_owner

In [ ]:
df.prev_owner

0        2 prev...
1             None
2        1 prev...
3        1 prev...
4        1 prev...
           ...
15914         None
15915    1 prev...
15916    1 prev...
15917         None
15918    1 prev...
Name: prev_owner, Length: 15919, dtype: object

In [ ]:
df.prev_owner.isnull().sum()

6828

In [ ]:
df[df["prev_owner"].isnull()].head() # BODY_TYPE SÜTUNUNDAKİ "NONE" DEĞERLERİ GÖSTERİR.

          url make_model short_description body_type  price        vat         km registration prev_owner  kW      hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
1   https:...    Audi A1  1.8 TF...           Sedans  14500  Price ...  80,000 km    03/2017         None NaN  141 kW  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, R...        NaN  ...    [\n4\n]    [\n058...  [\n, A...    [\n1,7...     [\n4\n]  [\n1,2...  [\nfro...   [\n, G...  [[5.6 ...   [\n129...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nLan...   [\n4 (...      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
9   https:...    Audi A1  SPORTB...           Sedans  17990       None  16,103 km    06/2017         None NaN   70 kW  [, Use...        NaN             NaN             NaN      \n3 mo...        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, W...        NaN  ...    [\n4\n]          NaN  [\n, A...    [\n999...         NaN        NaN        NaN   [\n, G...        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN             [\nCli...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
10  https:...    Audi A1  SPORTB...           Sedans  18500  VAT de...  11,300 km    05/2018         None NaN   85 kW  [, Use...        NaN             NaN             NaN            NaN         \n          NaN            []  \nAudi\n  [\n, A...  [\n111...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [\n, D...  [[4 l/...   [\n105...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\naut...         NaN      [\n7\n]  [\nIta...             NaN                     NaN               NaN              NaN          NaN                           NaN
13  https:...    Audi A1  1.4 TF...           Sedans  18399       None  45,764 km    06/2016         None NaN  112 kW  [, Use...        NaN             NaN             NaN      \n12 m...        NaN          NaN            []  \nAudi\n  [\n, A...  [\nsca...    [\n, 2...          [\n, G...        NaN  ...    [\n4\n]          NaN  [\n, A...    [\n1,3...         NaN        NaN        NaN   [\n, G...        NaN         NaN          NaN      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nMar...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
16  https:...    Audi A1  SPB 1....           Sedans  18900  VAT de...   9,752 km    06/2018         None NaN   85 kW  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN            []  \nAudi\n  [\n, A...  [\n256...    [\n, 2...          [\n, B...        NaN  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,1...  [\nfro...   [\n, D...  [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [Centr...             [\nDEK...         NaN      [\n5\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[5 rows x 54 columns]

In [ ]:
null_columns=df.columns[df.isnull().any()]
df[df["prev_owner"].isnull()][null_columns].head()

   short_description body_type        vat prev_owner  kW       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle Offer Number First Registration Body Color Paint Type Body Color Original Upholstery       Body Nr. of Doors Nr. of Seats Model Code Displacement Cylinders     Weight Drive chain Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
1   1.8 TF...           Sedans  Price ...       None NaN  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN                 NaN    [\n, 2...          [\n, R...        NaN        NaN           [\nClo...  [\n, S...    [\n3\n]      [\n4\n]    [\n058...  [\n1,7...     [\n4\n]  [\n1,2...  [\nfro...   [[5.6 ...   [\n129...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n4 (...      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
9   SPORTB...           Sedans       None       None NaN  [, Use...        NaN             NaN             NaN      \n3 mo...        NaN          NaN                 NaN    [\n, 2...          [\n, W...        NaN  [\nBla...                 NaN  [\n, S...    [\n5\n]      [\n4\n]          NaN  [\n999...         NaN        NaN        NaN         NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
10  SPORTB...           Sedans  VAT de...       None NaN  [, Use...        NaN             NaN             NaN            NaN         \n          NaN           [\n111...    [\n, 2...          [\n, B...  [\nMet...  [\nNer...           [\nClo...  [\n, S...    [\n3\n]      [\n4\n]          NaN  [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [[4 l/...   [\n105...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN      [\n7\n]  [\nIta...             NaN                     NaN               NaN              NaN          NaN                           NaN
13  1.4 TF...           Sedans       None       None NaN  [, Use...        NaN             NaN             NaN      \n12 m...        NaN          NaN           [\nsca...    [\n, 2...          [\n, G...        NaN  [\nGri...                 NaN  [\n, S...    [\n3\n]      [\n4\n]          NaN  [\n1,3...         NaN        NaN        NaN         NaN         NaN          NaN      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
16  SPB 1....           Sedans  VAT de...       None NaN  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN           [\n256...    [\n, 2...          [\n, B...        NaN  [\nAzz...                 NaN  [\n, S...    [\n5\n]      [\n4\n]          NaN  [\n1,5...     [\n4\n]  [\n1,1...  [\nfro...   [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [Centr...                   NaN      [\n5\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

In [ ]:
df.prev_owner.isnull().head()

0    False
1     True
2    False
3    False
4    False
Name: prev_owner, dtype: bool

In [ ]:
df.prev_owner.isnull().to_frame().head()

   prev_owner
0      False
1       True
2      False
3      False
4      False

In [ ]:
df['prev_owner'].value_counts(dropna=False).to_frame()

            prev_owner
1 previ...       8294
NaN              6828
2 previ...        778
3 previ...         17
4 previ...          2

In [ ]:
# value_counts percentage view

df['prev_owner'].value_counts(normalize=True, dropna=False).to_frame()

            prev_owner
1 previ...   0.521013
NaN          0.428921
2 previ...   0.048872
3 previ...   0.001068
4 previ...   0.000126

In [265]:
df.prev_owner.value_counts(dropna=False).head()

1 previous owner     8294
NaN                  6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64

In [313]:
df.duplicated("prev_owner").value_counts().to_frame()  # There are 10 each duplicated rows and these rows should be unique.

           0
True   15914
False      5

In [314]:
df[df.duplicated("prev_owner", keep='first').to_frame()]

       url make_model short_description body_type  price  vat   km registration prev_owner  kW   hp Type Previous Owners Next Inspection Inspection new Warranty Full Service Non-smoking Vehicle null Make Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders Weight Drive chain Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
0      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
1      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
2      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4      NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
...    ...        ...        ...              ...    ...  ...  ...        ...          ...  ..  ...  ...        ...             ...             ...          ...        ...          ...           ...  ...   ...        ...          ...                ...        ...  ...        ...          ...        ...          ...         ...    ...        ...   ...        ...         ...          ...            ...                       ...                       ...        ...                   ...         ...       ...        ...             ...                     ...               ...              ...          ...                           ...
15914  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
15915  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
15916  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
15917  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
15918  NaN        NaN        NaN              NaN    NaN  NaN  NaN        NaN          NaN NaN  NaN  NaN        NaN             NaN             NaN          NaN        NaN          NaN           NaN  NaN   NaN        NaN          NaN                NaN        NaN  ...        NaN          NaN        NaN          NaN         NaN    NaN        NaN   NaN        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN                   NaN         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[15919 rows x 54 columns]

In [315]:
df[df["prev_owner"].duplicated()].head() # DUBLİKASYON SÜTUNLARI GÖSTERİR.

         url make_model short_description  body_type  price        vat         km registration prev_owner  kW     hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
3  https:...    Audi A1  1.4 TD...            Sedans  14500       None  73,000 km    08/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,4...     [\n3\n]  [\n1,1...        NaN   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air s...                 [Bluet...                 [Alloy...  [ABS, ...             [\nAud...         NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4  https:...    Audi A1  Sportb...            Sedans  16790       None  16,200 km    05/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\nC16...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]        NaN  [\nfro...   [\n, D...  [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, T...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
5  https:...    Audi A1  1.6 TD...            Sedans  15090       None  63,668 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\nJV0...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN        NaN   [\n, D...  [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nSic...   [\n4 (...          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
6  https:...    Audi A1  Sportb...         Statio...  16422  VAT de...  62,111 km    03/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN       [\nYes...            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\n200...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]        NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n98 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nRED...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
7  https:...    Audi A1  Sportb...           Compact  14480  VAT de...  14,986 km    02/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...          NaN            []  \nAudi\n  [\n, A...  [\n183...    [\n, 2...          [\n, R...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...         NaN        NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [ABS, ...             [\n, A...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[5 rows x 54 columns]

In [316]:
duplicate = df[df.duplicated("prev_owner")]   # ALT ALTA YAZILMIŞ DUBLİKASYON SATIR YOK GİBİ.
print("Duplicate Rows :")
duplicate.head(10)

Duplicate Rows :

          url make_model short_description  body_type  price        vat         km registration prev_owner  kW     hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
3   https:...    Audi A1  1.4 TD...            Sedans  14500       None  73,000 km    08/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,4...     [\n3\n]  [\n1,1...        NaN   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air s...                 [Bluet...                 [Alloy...  [ABS, ...             [\nAud...         NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4   https:...    Audi A1  Sportb...            Sedans  16790       None  16,200 km    05/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\nC16...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]        NaN  [\nfro...   [\n, D...  [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, T...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
5   https:...    Audi A1  1.6 TD...            Sedans  15090       None  63,668 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\nJV0...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...         NaN        NaN        NaN   [\n, D...  [[3.5 ...   [\n92 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nSic...   [\n4 (...          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
6   https:...    Audi A1  Sportb...         Statio...  16422  VAT de...  62,111 km    03/2016    1 prev... NaN  85 kW  [, Use...      \n1\n             NaN       [\nYes...            NaN  [\n, \...    [\n, \...            []  \nAudi\n  [\n, A...  [\n200...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]        NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n98 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\nRED...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN
7   https:...    Audi A1  Sportb...           Compact  14480  VAT de...  14,986 km    02/2016    1 prev... NaN  66 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...          NaN            []  \nAudi\n  [\n, A...  [\n183...    [\n, 2...          [\n, R...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...         NaN        NaN  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [ABS, ...             [\n, A...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
8   https:...    Audi A1  SPB 1....            Sedans  16700       None  57,000 km    02/2016    1 prev... NaN  85 kW  [, Use...      \n1\n       [\n02/...             NaN      [\n12 ...        NaN          NaN            []  \nAudi\n  [\n, A...  [\n115...    [\n, 2...          [\n, G...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [\n, D...  [[3.7 ...   [\n97 ...    [\nEur...      [Air c...                   [Radio]                 [Alloy...  [ABS, ...             [\nAut...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
9   https:...    Audi A1  SPORTB...            Sedans  17990       None  16,103 km    06/2017         None NaN  70 kW  [, Use...        NaN             NaN             NaN      \n3 mo...        NaN          NaN            []  \nAudi\n  [\n, A...        NaN    [\n, 2...          [\n, W...        NaN  ...    [\n4\n]          NaN  [\n, A...    [\n999...         NaN        NaN        NaN   [\n, G...        NaN         NaN          NaN            NaN                       NaN                       NaN        NaN             [\nCli...         NaN      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
10  https:...    Audi A1  SPORTB...            Sedans  18500  VAT de...  11,300 km    05/2018         None NaN  85 kW  [, Use...        NaN             NaN             NaN            NaN         \n          NaN            []  \nAudi\n  [\n, A...  [\n111...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n4\n]          NaN  [\n, A...    [\n1,5...     [\n4\n]  [\n1,2...  [\nfro...   [\n, D...  [[4 l/...   [\n105...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\naut...         NaN      [\n7\n]  [\nIta...             NaN                     NaN               NaN              NaN          NaN                           NaN
11  https:...    Audi A1  Sportb...            Sedans  17990       None  26,415 km    05/2016    1 prev... NaN  92 kW  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]            []  \nAudi\n  [\n, A...  [\n125...    [\n, 2...          [\n, S...  [\nUni...  ...        NaN    [\n058...  [\n, A...    [\n1,3...     [\n4\n]        NaN  [\nfro...   [\n, S...  [[4.9 ...   [\n112...    [\nEur...      [Air c...                 [CD pl...                 [Alloy...  [ABS, ...             [\n, A...         NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
12  https:...    Audi A1  Sportb...            Sedans  18380       None  31,600 km    09/2016    1 prev... NaN  92 kW  [, Use...      \n1\n       [\n09/...             NaN      [\n, \...        NaN    [\n, \...            []  \nAudi\n  [\n, A...  [\n86G...    [\n, 2...          [\n, W...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,3...     [\n4\n]        NaN  [\nfro...   [\n, R...  [[4.9 ...   [\n112...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, H...         NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN

[10 rows x 54 columns]

In [317]:
df.duplicated("prev_owner").value_counts()  # There are 5917 each duplicated rows and these rows should be unique.

True     15914
False        5
dtype: int64

## 2.10.kW

In [318]:
df.kW.head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: kW, dtype: float64

In [319]:
df.kW.isnull().sum()

15919

In [320]:
null_columns=df.columns[df.isnull().any()]
df[df["kW"].isnull()][null_columns].head()

  short_description body_type        vat prev_owner  kW       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle Offer Number First Registration Body Color Paint Type Body Color Original Upholstery       Body Nr. of Doors Nr. of Seats Model Code Displacement Cylinders     Weight Drive chain Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n Emission Label    Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
0  Sportb...           Sedans  VAT de...  2 prev... NaN  [, Use...      \n2\n       [\n06/...       [\nYes...      [\n, \...   [\n, \n]     [\n, \n]           [\nLR-...    [\n, 2...          [\n, B...  [\nMet...  [\nMyt...           [\nClo...  [\n, S...    [\n5\n]      [\n5\n]    [\n058...  [\n1,4...     [\n3\n]  [\n1,2...  [\nfro...   [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
1  1.8 TF...           Sedans  Price ...       None NaN  [, Use...        NaN             NaN             NaN            NaN        NaN          NaN                 NaN    [\n, 2...          [\n, R...        NaN        NaN           [\nClo...  [\n, S...    [\n3\n]      [\n4\n]    [\n058...  [\n1,7...     [\n4\n]  [\n1,2...  [\nfro...   [[5.6 ...   [\n129...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n4 (...      [\n7\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
2  Sportb...           Sedans  VAT de...  1 prev... NaN  [, Use...      \n1\n             NaN             NaN      [\n, \...        NaN          NaN           [\nAM-...    [\n, 2...          [\n, B...  [\nMet...  [\nmyt...           [\nClo...  [\n, S...    [\n4\n]      [\n4\n]          NaN  [\n1,5...         NaN        NaN  [\nfro...   [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [MP3, ...                 [Alloy...  [ABS, ...             [\n4 (...          NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
3  1.4 TD...           Sedans       None  1 prev... NaN  [, Use...      \n1\n             NaN             NaN            NaN  [\n, \...    [\n, \...                 NaN    [\n, 2...          [\n, B...  [\nMet...        NaN                 NaN  [\n, S...    [\n3\n]      [\n4\n]          NaN  [\n1,4...     [\n3\n]  [\n1,1...        NaN   [[3.8 ...   [\n99 ...    [\nEur...      [Air s...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN      [\n6\n]        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN
4  Sportb...           Sedans       None  1 prev... NaN  [, Use...      \n1\n             NaN       [\nYes...      [\n, \...  [\n, \...     [\n, \n]           [\nC16...    [\n, 2...          [\n, B...  [\nMet...  [\nMyt...           [\nClo...  [\n, S...    [\n5\n]      [\n5\n]    [\n058...  [\n1,4...     [\n3\n]        NaN  [\nfro...   [[4.1 ...   [\n109...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...                   NaN          NaN  [\nGer...             NaN                     NaN               NaN              NaN          NaN                           NaN

In [321]:
df.kW.isnull().head(372-379)

0        True
1        True
2        True
3        True
4        True
         ...
15907    True
15908    True
15909    True
15910    True
15911    True
Name: kW, Length: 15912, dtype: bool

In [322]:
df.kW.value_counts(dropna=False).head()

NaN    15919
Name: kW, dtype: int64

In [323]:
df.duplicated("kW").value_counts()  # There are 5917 each duplicated rows and these rows should be unique.

True     15918
False        1
dtype: int64

In [324]:
df.duplicated("kW", keep='first').head()

0    False
1     True
2     True
3     True
4     True
dtype: bool

In [325]:
df.duplicated(subset=['kW']).head()

0    False
1     True
2     True
3     True
4     True
dtype: bool

In [326]:
df.drop_duplicates(subset=['kW']).head()

         url make_model short_description body_type  price        vat         km registration prev_owner  kW     hp       Type Previous Owners Next Inspection Inspection new   Warranty Full Service Non-smoking Vehicle null      Make      Model Offer Number First Registration Body Color Paint Type  ... Nr. of Seats Model Code Gearing Type Displacement Cylinders     Weight Drive chain       Fuel Consumption CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n \nSafety & Security\n description Emission Label Gears Country version Electricity consumption Last Service Date Other Fuel Types Availability Last Timing Belt Service Date Available from
0  https:...    Audi A1  Sportb...           Sedans  15770  VAT de...  56,013 km    01/2016    2 prev... NaN  66 kW  [, Use...      \n2\n       [\n06/...       [\nYes...      [\n, \...   [\n, \n]     [\n, \n]            []  \nAudi\n  [\n, A...  [\nLR-...    [\n, 2...          [\n, B...  [\nMet...  ...    [\n5\n]    [\n058...  [\n, A...    [\n1,4...     [\n3\n]  [\n1,2...  [\nfro...   [\n, D...  [[3.8 ...   [\n99 ...    [\nEur...      [Air c...                 [Bluet...                 [Alloy...  [ABS, ...             [\n, S...         NaN       NaN        NaN             NaN                     NaN               NaN              NaN          NaN                           NaN

[1 rows x 54 columns]

In [327]:
df["kW"].shape

(15919,)

## 2.11.hp

## 2.12.Type

In [231]:
df["Type"]

0        [, Use...
1        [, Use...
2        [, Use...
3        [, Use...
4        [, Use...
           ...
15914    [, New...
15915    [, Use...
15916    [, Pre...
15917    [, Pre...
15918    [, Dem...
Name: Type, Length: 15919, dtype: object

In [239]:
df.Type.isnull().sum()

2

In [234]:
df.Type.isnull().head()

0    False
1    False
2    False
3    False
4    False
Name: Type, dtype: bool

str

In [240]:
df.Type.value_counts(dropna=False).head()

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[, Used, , Diesel (Particulate Filter)]    3475
[, Used, , Diesel]                         2516
[, Used, , Gasoline]                       2367
[, Used, , Super 95]                       1818
[, Pre-registered, , Super 95]              500
Name: Type, dtype: int64

In [238]:
type("Type")

str

In [241]:
df.Type.str[0].str.strip('[,')

0
1
2
3
4
        ..
15914
15915
15916
15917
15918
Name: Type, Length: 15919, dtype: object

In [242]:
df.Type.value_counts()

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[, Used, , Diesel (Particulate Filter)]                                                                                                       3475
[, Used, , Diesel]                                                                                                                            2516
[, Used, , Gasoline]                                                                                                                          2367
[, Used, , Super 95]                                                                                                                          1818
[, Pre-registered, , Super 95]                                                                                                                 500
[, New, , Super 95]                                                                                                                            497
[, Employee's car, , Diesel (Particulate Filter)]                                                                                              343
[, New, , Gasoline]                                                                                                                            340
[, Used, , Super 95 / Regular/Benzine 91]                                                                                                      324
[, Employee's car, , Super 95]                                                                                                                 264
[, Demonstration, , Super 95]                                                                                                                  259
[, Pre-registered, , Gasoline]                                                                                                                 198
[, Pre-registered, , Diesel (Particulate Filter)]                                                                                              189
[, New, , Diesel (Particulate Filter)]                                                                                                         179
[, Pre-registered, , Diesel]                                                                                                                   160
[, Demonstration, , Gasoline]                                                                                                                  158
[, Employee's car, , Diesel]                                                                                                                   139
[, New, , Super 95 (Particulate Filter)]                                                                                                       130
[, Demonstration, , Diesel (Particulate Filter)]                                                                                               129
[, Used, , Super E10 95]                                                                                                                       122
[, New, , Diesel]                                                                                                                              122
[, Used, , Regular/Benzine 91]                                                                                                                 122
[, Employee's car, , Gasoline]                                                                                                                 112
[, New, , Super E10 95]                                                                                                                         97
[, New, , Regular/Benzine 91]                                                                                                                   83
[, Employee's car, , Regular/Benzine 91]                                                                                                        77
[, New, , Regular/Benzine 91 (Particulate Filter)]                                                                                              73
[, Used, , Super 95 / Super E10 95]                                                                                                             70
[, Pre-registered, , Super 95 (Particulate Filter)]                                                                                             61
[, Pre-registered, , Super E10 95]                                                                                                              55
[, Demonstration, , Super 95 / Regular/Benzine 91]                                                                                              49
[, Demonstration, , Diesel]                                                                                                                     45
[, Used, , Super 95 (Particulate Filter)]                                                                                                       39
[, Used, , Super 95 / Super Plus 98]                                                                                                            38
[, Demonstration, , Regular/Benzine 91]                                                                                                         36
[, Pre-registered, , Regular/Benzine 91]                                                                                                        36
[, Employee's car, , Super E10 95]                                                                                                              33
[, Demonstration, , Super 95 (Particulate Filter)]                                                                                              32
[, Pre-registered, , Gasoline (Particulate Filter)]                                                                                             28
[, Used, , CNG]                                                                                                                                 27
[, Pre-registered, , Super 95 / Regular/Benzine 91]                                                                                             27
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98]                                                                         25
[, Demonstration, , Super E10 95]                                                                                                               24
[, Used, , Gasoline (Particulate Filter)]                                                                                                       23
[, Pre-registered, , Super 95 / Super E10 95]                                                                                                   22
[, New, , Super 95 / Super E10 95]                                                                                                              21
[, New, , Super 95 / Regular/Benzine 91]                                                                                                        21
[, New, , Super 95 / Super Plus 98]                                                                                                             20
[, Used, , Super E10 95 / Super 95]                                                                                                             18
[, Pre-registered, , Super 95 / Super E10 95 (Particulate Filter)]                                                                              16
[, Demonstration, , Super 95 / Super E10 95]                                                                                                    16
[, New, , Gasoline (Particulate Filter)]                                                                                                        15
[, Pre-registered, , Super 95 / Super Plus 98]                                                                                                  15
[, Employee's car, , Regular/Benzine 91 (Particulate Filter)]                                                                                   12
[, Demonstration, , Super 95 / Super Plus 98]                                                                                                   12
[, Used, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super E10 95 / Super Plus E10 98]                           12
[, New, , Super E10 95 / Super 95]                                                                                                              12
[, Pre-registered, , Super E10 95 / Super 95 / Super Plus 98 / Super Plus E10 98]                                                               11
[, Used, , LPG]                                                                                                                                 10
[, Employee's car, , Gasoline (Particulate Filter)]                                                                                             10
[, Demonstration, , Regular/Benzine 91 (Particulate Filter)]                                                                                     9
[, Used, , Super E10 95 / Super 95 / Super Plus 98 / Super Plus E10 98]                                                                          8
[, Demonstration, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98]                                                                 8
[, Used, , Liquid petroleum gas (LPG)]                                                                                                           7
[, Pre-registered, , Regular/Benzine 91 / Regular/Benzine E10 91]                                                                                7
[, Employee's car, , Super 95 (Particulate Filter)]                                                                                              6
[, Used, , Regular/Benzine E10 91]                                                                                                               5
[, New, , Super 95 / Super E10 95 (Particulate Filter)]                                                                                          5
[, Used, , Super 95 / Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super E10 95 / Super Plus E10 98]                            5
[, Used, , Super 95 / Super Plus 98 (Particulate Filter)]                                                                                        5
[, New, , Super 95 / Super Plus 98 (Particulate Filter)]                                                                                         5
[, New, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98]                                                                           5
[, New, , CNG]                                                                                                                                   5
[, Used, , Super E10 95 / Super Plus E10 98]                                                                                                     4
[, Used, , Super 95 / Super E10 95 / Super Plus E10 98 / Super Plus 98]                                                                          4
[, Used, , Electric/Gasoline]                                                                                                                    4
[, Demonstration, , Super 95 / Super Plus 98 (Particulate Filter)]                                                                               4
[, Used, , Regular/Benzine 91 (Particulate Filter)]                                                                                              3
[, Pre-registered, , Super E10 95 / Super 95 / Super Plus 98 / Super Plus E10 98 (Particulate Filter)]                                           3
[, Used, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95]                            3
[, Pre-registered, , Regular/Benzine E10 91]                                                                                                     3
[, Used, , Super 95 / Super Plus 98 / Super E10 95]                                                                                              3
[, Used, , Super 95 / Super E10 95 (Particulate Filter)]                                                                                         3
[, Employee's car, , Super 95 / Regular/Benzine 91]                                                                                              3
[, Pre-registered, , Regular/Benzine 91 (Particulate Filter)]                                                                                    3
[, Used, , Super 95 / Super Plus 98 / Super Plus E10 98 / Super E10 95]                                                                          3
[, Demonstration, , Super E10 95 / Super 95]                                                                                                     3
[, Pre-registered, , LPG]                                                                                                                        3
[, Used, , Others]                                                                                                                               3
[, Employee's car, , Super E10 95 / Super 95]                                                                                                    3
[, New, , Super 95 / Super Plus 98 / Super E10 95]                                                                                               3
[, Pre-registered, , Liquid petroleum gas (LPG)]                                                                                                 3
[, New, , Super E10 95 (Particulate Filter)]                                                                                                     3
[, Employee's car, , Super 95 / Super E10 95]                                                                                                    2
[, Pre-registered, , Super E10 95 / Super 95]                                                                                                    2
[, Pre-registered, , Super 95 / Super Plus 98 / Super E10 95]                                                                                    2
[, Employee's car, , LPG]                                                                                                                        2
[, Pre-registered, , Super E10 95 / Super 95 / Super Plus 98]                                                                                    2
[, Used, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Super Plus E10 98 / Super E10 95 / Regular/Benzine E10 91]                            2
[, New, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                                                      2
[, New, , Super Plus 98]                                                                                                                         2
[, Pre-registered, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98]                                                                2
[, New, , Regular/Benzine E10 91]                                                                                                                2
[, Used, , Super 95 / Regular/Benzine 91 / Super Plus 98]                                                                                        2
[, Pre-registered, , Super Plus 98]                                                                                                              2
[, Used, , Super Plus 98]                                                                                                                        2
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                                                     1
[, Demonstration, , Super Plus 98 / Regular/Benzine 91]                                                                                          1
[, Employee's car, , Super E10 95 / Super 95 / Super Plus 98]                                                                                    1
[, Used, , Super 95 / Super E10 95 / Super Plus 98]                                                                                              1
[, Pre-registered, , CNG]                                                                                                                        1
[, Used, , Others (Particulate Filter)]                                                                                                          1
[, Pre-registered, , Super E10 95 (Particulate Filter)]                                                                                          1
[, New, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super E10 95 / Super Plus E10 98]                             1
[, Used, , Super 95 / Super Plus 98 / Super Plus E10 98]                                                                                         1
[, Demonstration, , Super E10 95 (Particulate Filter)]                                                                                           1
[, Used, , Super 95 / Regular/Benzine E10 91 / Super E10 95]                                                                                     1
[, Used, , Super E10 95 / Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98]                            1
[, Pre-registered, , CNG (Particulate Filter)]                                                                                                   1
[, Pre-registered, , Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91]                                                                     1
[, Used, , Super 95 / Super E10 95 / Super Plus E10 98]                                                                                          1
[, Pre-registered, , Regular/Benzine 91 / Super 95]                                                                                              1
[, Used, , Domestic gas H]                                                                                                                       1
[, Demonstration, , Super 95 / Super Plus 98 / Super Plus E10 98 / Super E10 95]                                                                 1
[, Demonstration, , Super Plus 98 / Super 95 / Super E10 95]                                                                                     1
[, Used, , Super E10 95 (Particulate Filter)]                                                                                                    1
[, New, , Super 95 / Biodiesel]                                                                                                                  1
[, Employee's car, , Others]                                                                                                                     1
[, Used, , CNG (Particulate Filter)]                                                                                                             1
[, Demonstration, , Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95 / Regular/Benzine 91]                   1
[, Used, , Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super 95 / Super E10 95 / Super Plus E10 98]                            1
[, New, , LPG]                                                                                                                                   1
[, Demonstration, , Super 95 / Regular/Benzine 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98 / Regular/Benzine E10 91]                   1
[, Used, , Regular/Benzine 91 / Super 95 / Super Plus 98]                                                                                        1
[, Pre-registered, , Biogas]                                                                                                                     1
[, Used, , Super 95 / Regular/Benzine 91 / Super E10 95 / Super Plus E10 98 / Super Plus 98]                                                     1

In [243]:
import re

In [251]:
# Function to clean the names
def Clean_names(Type):
    # Search for opening bracket in the name followed by
    # any characters repeated any number of times
    if re.search('[,', Type):
  
        # Extract the position of beginning of pattern
        pos = re.search('[,', Type).start()
  
        # return the cleaned name
        return Type[:pos]
  
    else:
        # if clean up needed return the same name
        return Type

In [258]:
# Updated the city columns
df['Type'] = df['Type'].apply(Clean_names())
  
# Print the updated dataframe
df['Type']

error: unterminated character set at position 0

In [250]:
conda install list

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

Note: you may need to restart the kernel to use updated packages.

PackagesNotFoundError: The following packages are not available from current channels:

  - list

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

## 2.13.Previous Owners

In [259]:
df.Previous Owners.head()

SyntaxError: invalid syntax (<ipython-input-259-33bbe36252dd>, line 1)

## 2.14. Next Inspection

## 2.15. Inspection new

## 2.16. Warranty

## 2.17.Full Service

## 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

# 2.18. Non-smoking Vehicle

In [9]:
df["Model"]

0            [\n, A1, \n]
1            [\n, A1, \n]
2            [\n, A1, \n]
3            [\n, A1, \n]
4            [\n, A1, \n]
               ...
15914    [\n, Espace, \n]
15915    [\n, Espace, \n]
15916    [\n, Espace, \n]
15917    [\n, Espace, \n]
15918    [\n, Espace, \n]
Name: Model, Length: 15919, dtype: object

In [11]:
df["url"]

0        https://www.autoscout24.com//offers/audi-a1-sp...
1        https://www.autoscout24.com//offers/audi-a1-1-...
2        https://www.autoscout24.com//offers/audi-a1-sp...
3        https://www.autoscout24.com//offers/audi-a1-1-...
4        https://www.autoscout24.com//offers/audi-a1-sp...
                               ...
15914    https://www.autoscout24.com//offers/renault-es...
15915    https://www.autoscout24.com//offers/renault-es...
15916    https://www.autoscout24.com//offers/renault-es...
15917    https://www.autoscout24.com//offers/renault-es...
15918    https://www.autoscout24.com//offers/renault-es...
Name: url, Length: 15919, dtype: object

In [12]:
df["null"].value_counts()

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[]    15919
Name: null, dtype: int64

In [13]:
df.index

RangeIndex(start=0, stop=15919, step=1)

In [14]:
df["registration"].value_counts()

-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2016     141
09/2018     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
12/2019       1
11/2019       1
Name: registration, dtype: int64

In [15]:
df["null"]

0        []
1        []
2        []
3        []
4        []
         ..
15914    []
15915    []
15916    []
15917    []
15918    []
Name: null, Length: 15919, dtype: object

In [16]:
df["null"].value_counts()  # komplesi null olduğundan bu sütun komple silinebilir.

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[]    15919
Name: null, dtype: int64

In [17]:
df["Model"]

0            [\n, A1, \n]
1            [\n, A1, \n]
2            [\n, A1, \n]
3            [\n, A1, \n]
4            [\n, A1, \n]
               ...
15914    [\n, Espace, \n]
15915    [\n, Espace, \n]
15916    [\n, Espace, \n]
15917    [\n, Espace, \n]
15918    [\n, Espace, \n]
Name: Model, Length: 15919, dtype: object

In [18]:
df["Model"].value_counts()  # \n'ler kaldırılmalı/silinmeli

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, A3, \n]          3097
[\n, A1, \n]          2614
[\n, Insignia, \n]    2598
[\n, Astra, \n]       2526
[\n, Corsa, \n]       2219
[\n, Clio, \n]        1839
[\n, Espace, \n]       991
[\n, Duster, \n]        34
[\n, A2, \n]             1
Name: Model, dtype: int64

In [19]:
df["Gearing Type"]

0        [\n, Automatic, \n]
1        [\n, Automatic, \n]
2        [\n, Automatic, \n]
3        [\n, Automatic, \n]
4        [\n, Automatic, \n]
                ...
15914    [\n, Automatic, \n]
15915    [\n, Automatic, \n]
15916    [\n, Automatic, \n]
15917    [\n, Automatic, \n]
15918    [\n, Automatic, \n]
Name: Gearing Type, Length: 15919, dtype: object

In [20]:
df["Gearing Type"].value_counts() # \n'ler kaldırılmalı/silinmeli

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Manual, \n]            8153
[\n, Automatic, \n]         7297
[\n, Semi-automatic, \n]     469
Name: Gearing Type, dtype: int64

In [21]:
df["Fuel"]

0                    [\n, Diesel (Particulate Filter), \n]
1                                       [\n, Gasoline, \n]
2                    [\n, Diesel (Particulate Filter), \n]
3                    [\n, Diesel (Particulate Filter), \n]
4                    [\n, Diesel (Particulate Filter), \n]
                               ...
15914                [\n, Diesel (Particulate Filter), \n]
15915    [\n, Super 95 / Super Plus 98 (Particulate Fil...
15916                                     [\n, Diesel, \n]
15917                                     [\n, Diesel, \n]
15918                                   [\n, Super 95, \n]
Name: Fuel, Length: 15919, dtype: object

In [22]:
df["Fuel"].value_counts() # \n'ler kaldırılmalı/silinmeli, çoklu benzin tiplerine işlem yapılmalı

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Diesel (Particulate Filter), \n]                                                                                  4315
[\n, Super 95, \n]                                                                                                     3338
[\n, Gasoline, \n]                                                                                                     3175
[\n, Diesel, \n]                                                                                                       2984
[\n, Super 95 / Regular/Benzine 91, \n]                                                                                 424
                                                                                                                       ...
[\n, Super 95 / Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95, \n]       1
[\n, Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super 95 / Super E10 95 / Super Plus E10 98, \n]       1
[\n, Regular/Benzine 91 / Super 95 / Super E10 95 / Regular/Benzine E10 91, \n]                                           1
[\n, Regular/Benzine 91 / Super 95 / Super Plus 98, \n]                                                                   1
[\n, Super 95 / Super E10 95 / Super Plus 98, \n]                                                                         1
Name: Fuel, Length: 77, dtype: int64

In [23]:
df["description"]

0        [\n, Sicherheit:,  , Deaktivierung für Beifahr...
1        [\nLangstreckenfahrzeug daher die hohe Kilomet...
2        [\n, Fahrzeug-Nummer: AM-95365,  , Ehem. UPE 2...
3        [\nAudi A1: , - 1e eigenaar , - Perfecte staat...
4        [\n, Technik & Sicherheit:, Xenon plus, Klimaa...
                               ...
15914    [\nVettura visionabile nella sede in Via Roma ...
15915    [\nDach: Panorama-Glas-Schiebedach, Lackierung...
15916    [\n, Getriebe:,  Automatik, Technik:,  Bordcom...
15917    [\nDEK:[2691331], Renault Espace Blue dCi 200C...
15918    [\n, Sicherheit Airbags:,  , Seitenairbag,  , ...
Name: description, Length: 15919, dtype: object

In [24]:
df["description"].value_counts()

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 636
[\n, \n]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            30
[\nSichern Sie sich diesen Opel Astra K 1.4 SIDI Turbo Innovation Start/Stop zum Top-Preis inklusive dem, AUTOHERO-RUNDUM-SORGLOS-PAKET,  , Infos:,  2.Hand, deutsche Auslieferung, Unfallfrei, scheckheftgepflegt, mindestens 12 Monate gültige HU und AU,  , Highlights,  , Rückfahrkamera,  , Voll-LED-Matrix-Scheinwerfer (IntelliLux),  , Audio-Navigationssystem Navi 900 Europa Touch,  , Spurassistent,  , Leichtmetallfelgen , Komfort,  , Sitzheizung vorn,  , Klimaautomatik 2-Zonen,  , Parkpilotsystem vorn und hinten,  , 6-Stufen Automatikgetriebe,  , Tempomat (Geschwindigkeits-Regelanlage) mit Begrenzer ,  , Berganfahrassistent ,  , Servolenkung,  , Lendenwirbelstütze elektropneumatisch für Fahrer ,  , Kopfstützen vorn und hinten ,  , Multifunktionslenkrad in Leder, beheizbar ,  , Mittelarmlehne vorn verschiebbar,  , Zentralverriegelung mit Fernbedienung,  , Fensterheber elektrisch vorn + hinten,  , Berganfahr-Assistent (HSA, Hill Start Assist), Multimedia,  , 8 Zoll Touchscreen-Farbdisplay,  , Verkehrszeichenerkennung,  , Audiostreaming ,  , Apple CarPlay und Android Auto,  , 6 Lautsprecher ,  , Bluetooth-Freisprecheinrichtung ,  , Sprachsteuerung,  , Bordcomputer,  , Multimedia-Schnittstelle (USB / AUX-IN), Licht und Sicht,  , Außenspiegel elektrisch verstell-, heiz- und anklappbar,  , Abbiegelicht,  , LED Tagfahrlicht,  , Nebelscheinwerfer,  , Ambientebeleuchtung,  , Innenrückspiegel automatisch abblendend,  , Fernlichtassistent und Leuchtweitenregulierung ,  , Licht und Regensensor ,  , Wärmeschutzverglasung hinten abgedunkelt (Solar-Protect),  , LED Heckleuchten , Sicherheit,  , Abstandswarner,  , Auffahrwarnsystem,  , Isofix-Aufnahmen für Kindersitz an Rücksitz,  , Frontkamera,  , Airbag für Fahrer- und Beifahrerseite,  , Wegfahrsperre,  , ...]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      27
[\n, Fahrzeugbeschreibung,  Sichern Sie sich diesen Renault Clio 1.6 TCE Energy Sport Trophy zum Top-Preis inklusive dem , AUTOHERO-RUNDUM-SORGLOS-PAKET,  , Infos:,  1.Hand, deutsche Auslieferung, Unfallfrei, scheckheftgepflegt,  , Highlights,  , Audio-Navigationssystem R-Link Evolution mit Touchscreen und Carminat TomTom,  , Sportsitze ,  , Sportfahrwerk,  , Scheinwerfer Full-LED , Komfort,  , Geschwindigkeits-Regelanlage (Tempomat) ,  , Klimaanlage,  , Einparkhilfe hinten,  , Multifunktionslenkrad (Sport/Leder) mit Schaltwippen/-tasten ,  , Fensterheber elektr. mit Impulsgeber links/rechts vorn,  , Zentralverriegelung / Startanlage Handsfree Entry & Drive ,  , Berganfahr-Assistent (HSA) , Multimedia,  , Audiosystem: Radio R & GO (Bluetooth, DAB-Tuner),  , Bordcomputer,  , Freisprecheinrichtung Bluetooth ,  , USB-Anschluss inkl. AUX-IN-Anschluss (Plug & Music) , Licht und Sicht,  , Außenspiegel elektr. verstell- und heizbar ,  , Licht- und Regensensor ,  , Tagfahrlicht LED ,  , Nebelscheinwerfer LED ,  , Coming-Home-Lichtfunktion ,  , Heckleuchten LED , Sicherheit,  , Isofix-Aufnahmen für Kindersitz ,  , Seitenairbag vorn,  , Wegfahrsperre,  , Differentialsperre,  , Bremsassistent ,  , Elektron. Stabilitäts-Programm (ESP),  , Anti-Blockier-System (ABS),  , Anti-Submarining-Airbag im Fond,  , Airbag Fahrer-/Beifahrerseite ,  , Differentialsperre ,  , Reifendruck-Kontrollsystem ,  , Untersteuerungskontrolle (USC) ,  , Antischlupfregelung (ASR) , Weiteres,  , Start/Stop-Anlage ,  , Servolenkung geschwindigkeitsabhängig,  , R.S. Drive (Fahrmodusschalter) ,  , Gepäckraumabdeckung / Rollo ,  , Heckdiffusor ,  , LM-Felgen ,  , Heckspoiler (Renault Sport) ,  , Pedale Aluminium ,  , Energierückgewinnung (Energy Smart Management) , ...]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       27
[\n, Fahrzeugbeschreibung,  Sichern Sie sich diesen Audi A1 1.4 TDI Design zum Top-Preis inklusive dem, AUTOHERO-RUNDUM-SORGLOS-PAKET,  , Infos:,  2. Hand, deutsche Auslieferung, Unfallfrei, scheckheftgepflegt ,  , Highlights,  , Leichtmetallfelgen,  , Sitzheizung vorn,  , Sportsitze vorn,  , Dynamik-Fahrwerk,  , Multi-Media-Interface MMI Navigation,  , Einparkhilfe hinten (APS),  , CO2-optimiert (Ausführung e, Ultra) ,  , Komfort,  , Klimaautomatik,  , Mittelarmlehne vorn mit Fach,  , Fensterheber elektrisch vorn,  , Zentralverriegelung mit Fernbedienung,  , Berganfahr-Assistent,  , Multifunktionslederlenkrad,  , Rücksitzlehne geteilt/klappbar,  , Sitze vorn höhenverstellbar ,  , Lendenwirbelstützen verstellbar ,  , Multimedia,  , Audi music interface,  , Fahrer-Informations-System (FIS),  , Bluetooth-Freisprecheinrichtung,  , Licht und Sicht,  , Außenspiegel elektrisch verstell- und heizbar, beide,  , Tagfahrlicht,  , Scheibenwaschdüsen heizbar,  , Licht- und Regensensor,  , Nebelscheinwerfer integriert,  , Wärmeschutzverglasung grün getönt,  , Heckleuchten LED,  , Sicherheit,  , Isofix-Aufnahmen für Kindersitz,  , Bremsassistent,  , Seitenairbag vorn,  , Reifenkontroll-Anzeige,  , Anti-Blockier-System (ABS),  , Wegfahrsperre (elektronisch),  , Airbag Fahrer-/Beifahrerseite,  , Antriebs-Schlupfregelung (ASR),  , Kopf-Airbag-System (Sideguard),  , Elektronische Differentialsperre (EDS),  , Elektronisches Stabilitäts-Programm (ESP),  , Weiteres,  , Start/Stop-Anlage,  , Wagenheber,  , Servolenkung,  , ...]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         27
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...

In [25]:
df.columns.strip()

AttributeError: 'Index' object has no attribute 'strip'

# Fuel

In [36]:
df["Fuel"].str.lstrip("[\n,")

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
15914   NaN
15915   NaN
15916   NaN
15917   NaN
15918   NaN
Name: Fuel, Length: 15919, dtype: float64

In [39]:
df["Fuel"].str.rstrip(", \n]")

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
15914   NaN
15915   NaN
15916   NaN
15917   NaN
15918   NaN
Name: Fuel, Length: 15919, dtype: float64

In [43]:
df["Fuel"].str.rsplit(", \n]")

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
15914   NaN
15915   NaN
15916   NaN
15917   NaN
15918   NaN
Name: Fuel, Length: 15919, dtype: float64

In [45]:
df["Fuel"].str.rsplit()

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
15914   NaN
15915   NaN
15916   NaN
15917   NaN
15918   NaN
Name: Fuel, Length: 15919, dtype: float64

In [48]:
df["Fuel"].str.split()

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
15914   NaN
15915   NaN
15916   NaN
15917   NaN
15918   NaN
Name: Fuel, Length: 15919, dtype: float64

In [49]:
df["Fuel"]

0                    [\n, Diesel (Particulate Filter), \n]
1                                       [\n, Gasoline, \n]
2                    [\n, Diesel (Particulate Filter), \n]
3                    [\n, Diesel (Particulate Filter), \n]
4                    [\n, Diesel (Particulate Filter), \n]
                               ...
15914                [\n, Diesel (Particulate Filter), \n]
15915    [\n, Super 95 / Super Plus 98 (Particulate Fil...
15916                                     [\n, Diesel, \n]
15917                                     [\n, Diesel, \n]
15918                                   [\n, Super 95, \n]
Name: Fuel, Length: 15919, dtype: object